### ISSUE TITLE
Create an easy way of selecting bindings for db.session()

### ISSUE THREAD

**Issue by stevenleeg** [mitsuhiko/flask-sqlalchemy#107]
As far as I'm aware, there is no easy way to switch between bindings for executing raw SQL statements:

    from flask.ext.sqlalchemy import SQLAlchemy
    
    # ...
    
    # Set up bindings
    app['SQLALCHEMY_BINDS'] = {
        "first": "...",
        "second": "..."
    }
    
    # Create the database object
    db = SQLAlchemy(app)
    
    # But which binding will this run on?
    db.session.execute("SELECT * FROM table")

It's certainly possible that I'm not finding this functionality. However if it doesn't already exist, I believe some way to switch/select bindings for sessions is a pretty necessary feature:

    session_first = db.get_session(bind = "first")
    session_second = db.get_session(bind = "second")

or

    db.session.execute(querystr, bind = "first")

Any thoughts?

**Comment by FelikZ** [comment]
@franklx this should be merged

**Comment by immunda** [comment]
Right you are @franklx, in #249.

**Comment by FelikZ** [comment]
@immunda great, but how I can use specific bind session?

Using a class by @franklx I can do:

    db.s_connection1.query(User)
    db.s_connection2.query(User)

How this merge will help me to achieve the same effect?

**Comment by Cheaterman** [comment]
I just used `db.get_engine(app, 'my_bind').execute(...)` with great success, for anyone interested.

So, I guess we're good? :-)

**Comment by shizidushu** [comment]
See https://github.com/pallets/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L735

In the definition of class SQLAlchemy, `self.session = self.create_scoped_session(session_options)`. We can use `session = db.create_scoped_session(options = {'bind': 'my_bind'})`. 

If the above is the right way to get session for a specified bind key, it should be documented.

**Comment by neevai** [comment]
The suggested solutions did not work for me.
This is what I did:

`
import flask_sqlalchemy

# ...

 app = flask.Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = service_a_database_uri
app.config['SQLALCHEMY_BINDS'] = {
    'service_b': service_b_database_uri,
    'service_c': service_c_database_uri
}

# ...

flask_sqlalchemy.SQLAlchemy(app)

# ...
 def create_scoped_session(app, bind_key):
    return app.extensions["sqlalchemy"].db.create_scoped_session(
                options={'bind': app.extensions["sqlalchemy"].connectors[bind_key]._engine})

service_a_session = create_scoped_session(app, 'service_a')
service_b_session = create_scoped_session(app, 'service_b')
`
