### ISSUE TITLE
Signal part is deprecated

### ISSUE THREAD

**Issue by reorx** [mitsuhiko/flask-sqlalchemy#110]
As SQLAlchemy announced that module on [this page](http://docs.sqlalchemy.org/en/rel_0_8/orm/deprecated.html) is deprecated,
consider refactor the signal part (`_SignallingSessionExtension`, `_SignalTrackingMapperExtension`) using new module `sqlalchemy.orm.events` documented in this page:

http://docs.sqlalchemy.org/en/rel_0_8/orm/events.html

**Comment by reorx** [comment]
@immunda Got a reason to close?

**Comment by davidism** [comment]
Events have been fixed in master and will be deprecated.  A new release is coming soon.

**Comment by reorx** [comment]
@davidism Got it, thank you :D
