### ISSUE TITLE
create_all and drop_all bind issues

### ISSUE THREAD

**Issue by galalex** [mitsuhiko/flask-sqlalchemy#126]
I think there might be an issue when passing `bind=None` to the `create_all` and `drop_all` methods.

> The create_all() and drop_all() methods by default operate on all declared binds, including the default one. This behavior can be customized by providing the bind parameter. It takes either a single bind name, '__all__' to refer to all binds or a list of binds. The default bind (SQLALCHEMY_DATABASE_URI) is named None:
>
> ~~~python
> >>> db.create_all()
> >>> db.create_all(bind=['users'])
> >>> db.create_all(bind='appmeta')
> >>> db.drop_all(bind=None)
> ~~~

When I used `db.create_all(bind=None)` it gave the error

~~~
TypeError: 'NoneType' object is not iterable`
caused by line 811 at the file: flask_sqlalchemy.py 
method: def _execute_for_all_tables(self, app, bind, operation):
~~~

I had to use `bind=[None]` to make it work.

Also, does it make sense for the default value to be `'__all__'`? Just wondering since the way I use it is to bind other external resources databases  (I had some awesome surprises creating my model inside production environments. ;) )

**Comment by davidism** [comment]
I cannot reproduce this issue

~~~python3
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)

db.create_all(bind=None)
~~~

It appears the code was already correct in 2011: b07f29dcd11515f043ccc67658205c5cf9355fe1.  I'll reopen this if you can come up with an example demonstrating the issue.
