### ISSUE TITLE
AttributeError: 'Session' object has no attribute '_model_changes'

### ISSUE THREAD

**Issue by yang** [mitsuhiko/flask-sqlalchemy#162]
I'm getting

```
AttributeError: 'Session' object has no attribute '_model_changes'
```

when trying to use a plain sqlalchemy Session elsewhere in unrelated code that is not flask-sqlalchemy-aware, e.g. simply calling:

```
sqlalchemy.orm.Session(sqlalchemy.create_engine('sqlite:///')).commit()
```

**Comment by immunda** [comment]
Fixed in master, soon to be released in 2.1
