### ISSUE TITLE
How to use versioned_session?

### ISSUE THREAD

**Issue by iurisilvio** [mitsuhiko/flask-sqlalchemy#175]
It was really difficult to find how to use versioned_session with Flask-SQLAlchemy.

It is easy, but it has no docs about it.

I found it with github search: https://github.com/sibande/humusha/blob/af53f61994791fb4e8bc3d9a13c39f41d1dd6b26/humusha/__init__.py

```
from history_meta import versioned_meta
from flask.ext.sqlalchemy import SQLAlchemy, Session

db = SQLAlchemy()
versioned_session(Session)
```

history_meta is a SQLAlchemy example: https://github.com/zzzeek/sqlalchemy/blob/f89d4d216bd7605c920b7b8a10ecde6bfea2238c/examples/versioned_history/history_meta.py

**Comment by immunda** [comment]
Any change you could submit a PR with some formal documentation about it?

**Comment by iurisilvio** [comment]
Sure! I'll write some docs about it. I have this setup in production,it'll be easy.

**Comment by davidism** [comment]
The "problem" with this method is that it enables versioning for *all* sessions, not just the Flask-SQLAlchemy one.  This is probably fine in most cases, but I'd rather see a solution that applies *just* to the extension.

**Comment by iurisilvio** [comment]
I'll try to apply the `versioned_session` only for Flask-SQLAlchemy sessions.

I don't know if it is possible.

**Comment by davidism** [comment]
You can apply `versioned_sessoin` to `flask_sqlalchemy.ScopedSession`.  This will apply the listener to all Flask-SQLAlchemy sessions, which usually shouldn't be a problem.  If you want to get *really* specific, you can subclass `SQLAlchemy` and override `create_session` to call this when creating each session instance.

**Comment by davidism** [comment]
The changes in #364 allow you to use this like `versioned_session(db.session)` now.
