### ISSUE TITLE
Listening for 'before_flush' throws sqlalchemy.exc.ArgumentError

### ISSUE THREAD

**Issue by acowlikeobject** [mitsuhiko/flask-sqlalchemy#182]
Registering a listener for 'before_commit' (and 'before_flush') like so, where:
```python
db = SQLAlchemy(app)
...
event.listen(db.session, 'before_commit', before_commit)
```

Throws the following exception:
```python
    @event.listens_for(db.session, "before_flush")
  File "/home/environments/python3/lib/python3.3/site-packages/sqlalchemy/event/api.py", line 68, in decorate
    listen(target, identifier, fn, *args, **kw)
  File "/home/environments/python3/lib/python3.3/site-packages/sqlalchemy/event/api.py", line 49, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "/home/environments/python3/lib/python3.3/site-packages/sqlalchemy/event/api.py", line 22, in _event_key
    tgt = evt_cls._accept_with(target)
  File "/home/environments/python3/lib/python3.3/site-packages/sqlalchemy/orm/events.py", line 1142, in _accept_with
    "Session event listen on a scoped_session "
sqlalchemy.exc.ArgumentError: Session event listen on a scoped_session requires that its creation callable is associated with the Session class.
```

Per the comment in this thread from Mike Bayer, it seems the issue is with the factory being passed to scoped_session not being a sessionmaker():
http://stackoverflow.com/questions/21322158/event-listener-on-scoped-session

Stepping through the code, it barfs in this method in line 1132 of sqlalchemy/orm/events.py:
```python
    @classmethod
    def _accept_with(cls, target):
        if isinstance(target, scoped_session):

            target = target.session_factory
            if not isinstance(target, sessionmaker) and \
                (
                    not isinstance(target, type) or
                    not issubclass(target, Session)
                ):
                raise exc.ArgumentError(
                            "Session event listen on a scoped_session "
                            "requires that its creation callable "
                            "is associated with the Session class.")
```

`db.session.session_factory` is of type `functools.partial`, which angers SQLAlchemy.

**Comment by kbussell** [comment]
You can work around this by registering the event handler on the underlying session class instead of on the created session object:

    event.listen(SignallingSession, 'before_commit', before_commit)

**Comment by nehresma** [comment]
@immunda bump.  I'm running into this as well.

**Comment by opyate** [comment]
Same here.

**Comment by davidism** [comment]
Hey everyone, in a surprising twist, you're still running into this issue because this issue is still open.  Use kbussell's workaround, or, better yet, submit a pull request if you care about this issue.

**Comment by opyate** [comment]
@davidism There's a PR here: #147 
@kbussell 's solution doesn't work for me. Stuff set in ```session.info``` gets lost between events.

**Comment by davidism** [comment]
The PR is actually at #148, and is not passing tests currently.  So it still needs work.

**Comment by opyate** [comment]
@davidism I brought it [up to date](https://github.com/opyate/flask-sqlalchemy/commit/5a8febacd2296a4b26106cc41fbaeca63b146fba), but just testing with my application too first before submitting a new PR.

**Comment by opyate** [comment]
OK, I'm still not happy. I do this:

    listen(db.session, 'after_commit', after_commit_handler)
    listen(db.session, 'after_flush', after_flush_handler)

```after_flush_handler``` sets something in ```session.info```, and ```after_commit_handler``` gets a ```KeyError``` on ```session.info``` for my value.

**Comment by davidism** [comment]
@opyate Consider adding some code so we can see what you're talking about and replicate your problem, as it seems related to this issue.

**Comment by opyate** [comment]
@davidism scrap that - I'm happy with it. I had a bug in the handlers (believe it or not, but the commit handler in some instances ran before the flush handler, so I had to check for the existence of the key and not assume it exists). After fixing the bug, I tried @kbussell 's solution again, and it works. Shall I still send a PR, or shall we just stick with @kbussell 's?
