### ISSUE TITLE
GitHub homepage URL links to Flask's docs instead of the extension's.

### ISSUE THREAD

**Issue by untitaker** [mitsuhiko/flask-sqlalchemy#203]
![2014-06-07-224358_621x119_scrot](https://cloud.githubusercontent.com/assets/837573/3209738/79ccd3b0-ee84-11e3-920a-2a40216d8497.png)

**Comment by svenstaro** [comment]
Duplicate of #65 but this one has pictures!

**Comment by jeffwidman** [comment]
Bump. I got confused because first Google result for the docs is the old pythonhosted.org docs for v 0.16, then looked here and didn't immediately see a link to updated docs either... figured it out, but what a mess.

**Comment by immunda** [comment]
Fixed :+1:

**Comment by jeffwidman** [comment]
:+1:
