### ISSUE TITLE
Add link to download documentation in PDF

### ISSUE THREAD

**Issue by Xumeiquer** [mitsuhiko/flask-sqlalchemy#209]
I was searching in the website documentation any link to download the documentation in pdf (or some other format) and I was not able to find it. It will be useful to check out the documentation off line.

**Comment by davidism** [comment]
The doc builder (pocoo/flask-docs) builds a pdf, located here:

* http://flask-sqlalchemy.pocoo.org/dev/.latex/Flask-SQLAlchemy.pdf
* http://flask-sqlalchemy.pocoo.org/2.1/.latex/Flask-SQLAlchemy.pdf
* etc.

I added a link in the sidebar, which should become visible on the dev docs at some point.  It's not currently possible to change the release docs.

Ping @mitsuhiko, do you want to move this to a "nicer" url?

**Comment by soerendip** [comment]
The links are dead.
