### ISSUE TITLE
"does not have a __table__ or __tablename__ specified" but the real issue is lack of ids

### ISSUE THREAD

**Issue by endolith** [mitsuhiko/flask-sqlalchemy#213]
I am completely new to SQL and in my first attempts I get the error:

> InvalidRequestError: Class <class 'flask_app.Votes'> does not have a __table__ or __tablename__ specified and does not inherit from an existing table-mapped class.

which is very strange because another tables works fine despite not having a __table__ or __tablename__

Then I find out, as described in http://stackoverflow.com/a/14595840/125507 that this is just a confusing error message and the real problem is lack of an `id` column, so please make the error message more helpful

**Comment by immunda** [comment]
Addressed in #258

**Comment by cgomezmendez** [comment]
I got this exact thing happening on version Flask-SQLAlchemy==2.3.0 and was pretty confuse.

**Comment by davidism** [comment]
@cgomezmendez please open a new issue with a reproducible example.
