### ISSUE TITLE
Update pythonhosted.org docs to 2.0

### ISSUE THREAD

**Issue by justinmayer** [mitsuhiko/flask-sqlalchemy#218]
The current top search result on Google for "Flask SQLAlchemy" is https://pythonhosted.org/Flask-SQLAlchemy/ , which shows version 0.16 documentation instead of the 2.0 version that was released today.

Might be best to update those docs to 2.0 (or re-direct to http://flask-sqlalchemy.pocoo.org/2.0/).

**Comment by rsyring** [comment]
came here to report this.  +1 :)

**Comment by jeffwidman** [comment]
+1
