### ISSUE TITLE
session_extensions argument on the SQLAlchemy constructor doesn't exist anymore

### ISSUE THREAD

**Issue by tonnydourado** [mitsuhiko/flask-sqlalchemy#220]
The docs for the [SQLAlchemy class](http://flask-sqlalchemy.pocoo.org/2.0/api/#flask.ext.sqlalchemy.SQLAlchemy) describing how to customize session behaviour are very outdated. The `session_extensions` argument exists only in the 0.16 version, and even the SessionExtensions from SQLAlchemy have been deprecated on 0.9.

Would be nice to have updated documentation, and also some example of how customization of the Session class should be done now.

UPDATE:

Digging in the code, just found out the proper way of using SessionExtensions:
```
    db = SQLAlchemy(session_options={'extension': [YourSessionExtension()]})
```

**Comment by davidism** [comment]
Session extension classes were deprecated in SQLAlchemy 0.7 in favor of session event callbacks.  I'll just remove this section altogether, the versioning example referred to doesn't even exist in that form anymore.
