### ISSUE TITLE
How do I override the default query class?

### ISSUE THREAD

**Issue by nickretallack** [mitsuhiko/flask-sqlalchemy#232]
I thought [this should work](https://gist.github.com/nickretallack/76bcd65cc0305abcd33b), but it doesn't.

**Comment by noah** [comment]
+1 basically I need to be able to write custom pagintion that does not encounter exponential complexity when using LIMIT and OFFSET.  See:

http://stackoverflow.com/questions/16916633/if-postgresql-count-is-always-slow-how-to-paginate-complex-queries
http://stackoverflow.com/questions/6618366/improving-offset-performance-in-postgresql

With hard-coded Query class this is badly broken for all but the most trivial applications.

**Comment by justanr** [comment]
Hm. Simply allowing setting a `query_class` parameter in `__init__` and passing it down to `_include_sqlalchemy` (and ultimately `_set_default_query_class`) goes most of the way towards fixing an issue like this. However, `Model` would still hard code the query class as `BaseQuery` and doing something like...

```python
class SQLAlchemy:
    def __init__(self, query_class=BaseQuery...):
        self.Model = self.make_declarative_base(...)
        # works but you know :/
        self.Model.query_class = query_class
```

[example of this sort of change](https://github.com/justanr/flask-sqlalchemy/commit/03ea88c43990dc4fb2254eadd1d91e28032952b5)

**Comment by immunda** [comment]
Thanks @justanr, helpful example.

This issue has now been eaten by #319.
