### ISSUE TITLE
Support Fast Testing

### ISSUE THREAD

**Issue by nickretallack** [mitsuhiko/flask-sqlalchemy#243]
SQLAlchemy has [a recipe for making test cases fast](http://docs.sqlalchemy.org/en/rel_0_9/orm/session.html#joining-a-session-into-an-external-transaction-such-as-for-test-suites).  Can FlaskSqlalchemy officially support this?

[This blog post](http://alexmic.net/flask-sqlalchemy-pytest/) describes one way to do the pattern in FlaskSqlalchemy, but it also no longer works.

I've got the pattern working in FlaskSqlalchemy before, but it required me to modify the source code of FlaskSqlalchemy, and recent updates to FlaskSqlalchemy have broken it.

Btw, I'd love to see a py.test example in the documentation.  I'm using py.test.

**Comment by candlerb** [comment]
See [this stackoverflow answer](http://stackoverflow.com/questions/26555125/rollback-transactions-not-working-with-py-test-and-flask#answer-26624146) - it contains a patch which works with flask-sqlalchemy 2.0 and pytest.

BTW, the same issue is also in pull request #168 although it no longer merges cleanly.

**Comment by jeffwidman** [comment]
Would love to see one of the multiple PR's mentioned above that fix this get merged...

**Comment by immunda** [comment]
#249 fixes this and is merged!
