### ISSUE TITLE
Support for naming convention?

### ISSUE THREAD

**Issue by xcompass** [mitsuhiko/flask-sqlalchemy#251]
Is there a way I can pass a naming convention to the metadata as shown here: http://docs.sqlalchemy.org/en/rel_0_9/core/constraints.html#configuring-constraint-naming-conventions?

**Comment by davidism** [comment]
Not directly, you need to subclass the SQLAlchemy class and change how it builds the base Model.

~~~py
from flask_sqlalchemy import SQLAlchemy as BaseSQLAlchemy, Model, _BoundDeclarativeMeta, _QueryProperty
from sqlalchemy import MetaData

class SQLAlchemy(BaseSQLAlchemy):
    def make_declarative_base(self):
        metadata = MetaData(naming_convention={
            'pk': 'pk_%(table_name)s',
            'fk': 'fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s',
            'uq': 'uq_%(table_name)s_%(column_0_name)s',
            'ix': 'ix_%(table_name)s_%(column_0_name)s',
            'ck': 'ck_%(table_name)s_%(constraint_name)s',
        })
        base = declarative_base(metadata=metadata, cls=Model, name='Model', metaclass=_BoundDeclarativeMeta)
        base.query = _QueryProperty(self)
        return base
~~~

**Comment by xcompass** [comment]
I tried the following, it seems working:

    db = SQLAlchemy()
    db.metadata.naming_convention = convention

Any potential problems?

**Comment by davidism** [comment]
I'm not sure if there are any issues with changing the metadata after creating the base, but if it works for you, go for it!  The example above is part of a larger set of overrides I use, I just simplified it.

**Comment by xcompass** [comment]
Thanks. I'll close it for now and will report if there is any problem.
