### ISSUE TITLE
Commit on teardown Bug

### ISSUE THREAD

**Issue by Siecje** [mitsuhiko/flask-sqlalchemy#262]
If commit() flushes and there is an exception, the next request will get a session that is in a partial rollback state and the request will fail.

https://github.com/mitsuhiko/flask-sqlalchemy/blob/e05ffe15c0f2feac19bb02f417b473fd83c88d71/flask_sqlalchemy/__init__.py#L778

**Comment by davidism** [comment]
Addressed by #216.

**Comment by immunda** [comment]
As @davidism put it!
