### ISSUE TITLE
migrate doesn't change Integer to BigInteger

### ISSUE THREAD

**Issue by 1905** [mitsuhiko/flask-sqlalchemy#264]
How to reproduce:
1. Create table with Integer field.
2. Change it in class to BigInteger.
3. Migrate, upgrade.
4. Field won't change.

To migrate properly you should remove field, migrate, upgrade and then add them as BigInteger. After that migration will be successful with field as BigInteger.

**Comment by 1905** [comment]
Found out it was Flask-Migrate bug

**Comment by davidism** [comment]
It's not a bug at all, nor is it due to Flask-Migrate.  Alembic requires you to set `compare_type=True` when configuring the migration context.
