### ISSUE TITLE
OperationalError when using reflect with uwsgi and multiple processes

### ISSUE THREAD

**Issue by kingd** [mitsuhiko/flask-sqlalchemy#268]
This is the minimal application. The problem appears when `db.reflect()` is used:

    from flask import Flask
    from flask.ext.sqlalchemy import SQLAlchemy

    app = Flask(__name__)
    app.config['DEBUG'] = True
    SQLALCHEMY_DATABASE_URI = '{0}://{1}:{2}@{3}:{4}/{5}?{6}'.format(
        'postgresql+psycopg2',  # driver
        'user',  # username
        'password',  # password
        'host',  # hostname
        '5432',  # port
        'database',  # database name
        'client_encoding=utf8'  # extra params
    )
    app.config['SQLALCHEMY_DATABASE_URI'] = SQLALCHEMY_DATABASE_URI

    db = SQLAlchemy(app)
    db.reflect(app=app)

    class User(db.Model):
        __tablename__ = 'user'

    @app.route("/")
    def home():
        result = db.session.query(User).first()
        print(result)
        return 'hello'

Errors that appear on every other request:

    sqlalchemy.exc.OperationalError: (OperationalError) SSL error: decryption failed or bad record mac
    sqlalchemy.exc.OperationalError: (OperationalError) SSL SYSCALL error: EOF detected
    sqlalchemy.exc.DatabaseError: (DatabaseError) SSL error: decryption failed or bad record mac

uwsgi conf:

    [uwsgi]
    socket = 127.0.0.1:8886
    master = true
    wsgi-file = hello.py
    callable = app
    virtualenv = /path/to/virtual/env
    processes = 8

As discussed here: http://bocribbz.com/post/64718784142/interfaceerror-interfaceerror-connection
this helps:

    @app.before_request
    def before_request():
        db.engine.dispose()

Or am i doing something wrong?

**Comment by xen** [comment]
This is well known feature of using psycopg2 with uwsgi, use `lazy-apps = true` option.

**Comment by kingd** [comment]
Tnx very much xen. I did find that option, but it makes uwsgi restart very slow so I "fixed it" by ``db.engine.dispose()`` in ``after_first_request`` function. I don't know if there are any sideeffects of that, but it's ok for now.
I guess this issue can be closed then.
