### ISSUE TITLE
Creating flask-sqlalchemy models that are reusable

### ISSUE THREAD

**Issue by makmanalp** [mitsuhiko/flask-sqlalchemy#269]
Hello, I have an interesting use case where I'm building a library of database models as well as a BaseModel and a BaseQuery that I plan on reusing in a bunch of different projects, e.g. `from blahblah_core.models import User`, but I'm struggling conceptually with what to use as my base class. In the library for the reusable models, do I use the flask-sqlalchemy `Query` and `Model` bases for all my stuff?

AFAIK, those require an instantiated `flask.ext.sqlalchemy.SQLAlchemy()`, even though that doesn't have to be tied to an app object yet. But the other project I'll be using these modules in will also have its own `SQLAlchemy`, right?

How do I structure this? Do I just give up and use the blahblah_core `SQLAlchemy`    instance in the new project? Or is there a way of decoupling the flask-sqlalchemy extension instance from the Model and Query so that I can use those models with /any/ SQLAlchemy instance? Could I maybe just make them raw SQLAlchemy objects - but then how would I tie those objects in so that flask-sqlalchemy knows about them?

Thanks in advance,
~mali

**Comment by makmanalp** [comment]
A gross way I can think of doing this is to wrap the model definitions in a function to form some kind of factory, where you pass in the SQLAlchemy instance you're using, which then creates your model classes using the given SQLAlchemy instance's Model and Query.

**Comment by makmanalp** [comment]
After a bit more research, these seem like they could be useful:

"How to use flask-sqlalchemy with existing sqlalchemy model?" - http://stackoverflow.com/questions/19119725/how-to-use-flask-sqlalchemy-with-existing-sqlalchemy-model

"Document how to use plain SQLAlchemy models with the Flask-SQLAlchemy session" #98 

https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L639

**Comment by tony** [comment]
https://github.com/mitsuhiko/flask-sqlalchemy/pull/250

**Comment by immunda** [comment]
Yep, overlaps with #250, closing.
