### ISSUE TITLE
Deprecate Flask-SQLAlchemy specific events

### ISSUE THREAD

**Issue by immunda** [mitsuhiko/flask-sqlalchemy#275]

**Comment by immunda** [comment]
#364 fixes problems that led to this thinking, and since `SQLALCHEMY_TRACK_MODIFICATIONS` will be disabled by default in future, there's no benefit in breaking compatibility for those that still want to make use of `_SessionSignalEvents`.

**Comment by jeffwidman** [comment]
Are there Flask-SQLAlchemy Signals that cover situations not covered by SQLAlchemy's built-in events? 

I get that you don't want to break compatibility--that makes sense. But if there's no advantage here other than backwards compatibility, wouldn't it still make sense to mark the Flask-SQLAlchemy signals as deprecated to discourage new apps from using them? No need to remove them right now, but still mark as deprecated.
