### ISSUE TITLE
AttributeError: 'SQLAlchemy' object has no attribute 'YEAR'

### ISSUE THREAD

**Issue by hussaintamboli** [mitsuhiko/flask-sqlalchemy#276]
`SQLAlchemy` has a datatype called `YEAR`. Why is it not there in `flask.ext.sqlalchemy`?

I also searched it in all the properties of it

    from flask.ext.sqlalchemy import SQLAlchemy
    db = SQLAlchemy()
    for i in dir(db):
        if 'year' in dir(i) or 'YEAR' in dir(i):
        print i

But didn't find it.

**Comment by davidism** [comment]
`YEAR` is a MySQL dialect-specific type.  You need to import it directly whether you're using Flask-SQLAlchemy or not.

    from sqlalchemy.dialects.mysql import YEAR

**Comment by hussaintamboli** [comment]
Okay. Thanks!
I don't know what dialects are but I will find out.
