### ISSUE TITLE
Not able to create a Boolean column

### ISSUE THREAD

**Issue by hussaintamboli** [mitsuhiko/flask-sqlalchemy#277]
With `sqlalchemy` I created a column with `boolean` data type in MySQL like this

    from sqlalchemy import Column BOOLEAN
    from sqlalchemy.sql import expression
    # .... some code ....
    is_deleted = Column(BOOLEAN, nullable=False, server_default=expression.false())
    # ... some code ....

How do I do the same using `flask-sqlalchemy`?

I have tried

    # this does not work
    is_deleted = db.Column(db.Boolean, nullable=False, server_default=expression.false())
    # this also does not work
    is_deleted = db.Column(db.BOOLEAN, nullable=False, server_default=expression.false())

But it created the column as `tinyint(1)`

**Comment by davidism** [comment]
[MySQL doesn't have a boolean type](https://dev.mysql.com/doc/refman/5.7/en/other-vendor-data-types.html), it's just written that way in SQLAlchemy for convenience.  Using `db.Boolean` is correct.

`Boolean` is a generic type that uses `mysql.BOOLEAN` when the engine dialect is mysql.  If you want to use `BOOLEAN` directly, import it just as you would when not using Flask-SQLAlchemy: `from sqlalchemy.dialects.mysql import BOOLEAN`.

**Comment by hussaintamboli** [comment]
Okay. Got it! I see that the creation statement uses `Boolean`

    2015-04-14 12:39:15,722 INFO sqlalchemy.engine.base.Engine
         # ... snip ...
         is_deleted BOOL NOT NULL DEFAULT false,
         # ... snip ...

But as I said the datatype in database is `tinyint(1)`

    | is_deleted      | tinyint(1)    | NO   |     | 0                 |

Thanks for the quick response.
