### ISSUE TITLE
self.app is only populated by the constructor

### ISSUE THREAD

**Issue by italomaia** [mitsuhiko/flask-sqlalchemy#279]
Hello folks, 
reading sqlalchemy code, I noticed self.app is only set in the constructor and not by init_app, why is that? Shouldn't both initialize self.app? Otherwise, I have to use a context to create my database. 

    self.app = app # <= this only happens inside __init__

**Comment by davidism** [comment]
This is common behavior for Flask extensions.  An extension can be registered with multiple apps, so you don't want to (re-)set `self.app` every time a new one is registered.  Typically you should always interact with your app inside an app context, but if you *really* don't like that and still want to use `init_app` separately, just set `db.app` afterwards.

**Comment by sh4nks** [comment]
TIL. This should be put somewhere in the flask docs.
I know this is not sqlalchemy specific but could you also explain why usually you just put this in your \__init__(self, app): ``self.app = app``
but then, self.app is never accessed. This somehow doesn't make senes for me. Why would you put it in there if it's never used anyway (i am taking about ``self.app``)?

**Comment by davidism** [comment]
It *is* mentioned in the Flask docs: http://flask.pocoo.org/docs/dev/extensiondev/

> As you noticed, init_app does not assign app to self. This is intentional! Class based Flask extensions must only store the application on the object when the application was passed to the constructor. This tells the extension: I am not interested in using multiple applications.
> 
> When the extension needs to find the current application and it does not have a reference to it, it must either use the current_app context local or change the API in a way that you can pass the application explicitly.

Flask-SQLAlchemy *does* use `self.app` with the exact behavior described above: https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L907

**Comment by sh4nks** [comment]
Thanks, now I am feeling a bit ashamed that I somehow didn't find this in the docs.. and sorry that I misused this issue for this.
