### ISSUE TITLE
How do I create one single table?

### ISSUE THREAD

**Issue by hussaintamboli** [mitsuhiko/flask-sqlalchemy#280]
Hello

I need to add one table to my db. Rest of my schema remains same. So far I was using 

    db.drop_all()
    db.create_all()

But this destroys and recreates my schema in turn deleting my whole data. But I don't want to delete my data. How do I gracefully add one single table?

**Comment by hussaintamboli** [comment]
`db.create_all` ultimately creates the new table without affecting the existing schema.

Does it alter the table if we change the model? I'll try it out myself.

**Comment by bastianh** [comment]
> Does it alter the table if we change the model? 

No.. if you want something like that look into Flask-Migrate

**Comment by hussaintamboli** [comment]
Okay. I will.
Thanks.
