### ISSUE TITLE
add adding app inside init_app

### ISSUE THREAD

**Issue by mplonski** [mitsuhiko/flask-sqlalchemy#283]
according to documentation I need to run

    db = SQLAlchemy()
    def create_app():
        app = Flask(__name__)
        db.init_app(app)
        return app

to initialize app. there's need to set

    self.app = app

insite init_app, because there's error if you don't set self.app.

**Comment by RonnyPfannschmidt** [comment]
that goes explicitly against using the db with more than one app,
whats the actual error?

**Comment by davidism** [comment]
Duplicates #279 (and probably many others).

**Comment by immunda** [comment]
Closin'
