### ISSUE TITLE
Allow explicit passing of binds to SignallingSession for testing purposes

### ISSUE THREAD

**Issue by johtso** [mitsuhiko/flask-sqlalchemy#311]
Would mean hacks like this would no longer be necessary to get testing to work: https://gist.github.com/alexmic/7857543#file-database-py

**Comment by chekunkov** [comment]
I believe issue was resolved by https://github.com/mitsuhiko/flask-sqlalchemy/commit/ac135c674fb2d4ae49395e15283be155e826b3ea

**Comment by immunda** [comment]
Right you are @chekunkov :+1:
