### ISSUE TITLE
get_app fails with init_app method

### ISSUE THREAD

**Issue by adamlwgriffiths** [mitsuhiko/flask-sqlalchemy#313]
The method described at the following URL (https://pythonhosted.org/Flask-SQLAlchemy/contexts.html), states that a global db can be later initialised with an application.

However, attempting to use that db for querying, inserting, etc, fails because `db.get_app()` triggers an exception.

db_test.py
```
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    db.init_app(app)
    return app

app = create_app()
db.get_app()
```

```
$ python db_test.py
Traceback (most recent call last):
  File "db_test.py", line 13, in <module>
    db.get_app()
  File "<snip>/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 845, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context
```

**Comment by RonnyPfannschmidt** [comment]
thats per design, enter a app context or use a single app instance,

**Comment by rlam3** [comment]
Is there a workaround for this?

**Comment by davidism** [comment]
@rlam3 

> enter a app context or use a single app instance

~~~python
with app.app_context():
    # do stuff that requires a current_app
~~~

**Comment by rlam3** [comment]
@davidism where exactly do you use with app.app_context? cause when i do it right after i do db.init_app(app) using a application factory method... it breaks because it is out of context... http://stackoverflow.com/questions/31706020/how-to-access-the-orm-with-celery-tasks

**Comment by davidism** [comment]
You were trying to use `current_app` to create an app context, which won't work because `current_app` requires an app context.

**Comment by rlam3** [comment]
@davidism When you mean create an app context, it would mean to create an app context every time this periodic task is run is what you mean?

Is there a way to find the app and get the context back from celery?
I'm doing the follwing following lines to create the celery instance. But when I try to call.. with celery.app.app_context()... It does not see the app at all... 
https://github.com/mattupstate/overholt/blob/master/overholt/factory.py#L51-L65


What I found worked, but I don't know if it was efficient was to do it or a good way to do this...:

Option 1

celery.app = app inside of make_celery

and inside of my periodic task i called onto the app context via

    # application.py
    def make_celery(app):
        celery = Celery(app.import_name, broker=app.config['CELERY_BROKER_URL'])
        celery.conf.update(app.config)
        TaskBase = celery.Task
        celery.app = app # assign the app to celery
        class ContextTask(TaskBase):
            abstract = True
            def __call__(self, *args, **kwargs):
                with app.app_context():
                    return TaskBase.__call__(self, *args, **kwargs)
        celery.Task = ContextTask
        return celery

    #tasks.py
    from main import app
    celery=create_celery(app)

    @periodic task
    with celery.app.app_context():
       # do some database stuff here


Option 2

    #tasks.py
    app = create_app() # create new app instance
    celery=create_celery(app)

    @periodic_task
    def do_something()
      with app.app_context():
      # do some datbase stuff here


Thanks for the help!
