### ISSUE TITLE
query.all() couldn't returns query when I use mysql in flask

### ISSUE THREAD

**Issue by dayiguizhen** [mitsuhiko/flask-sqlalchemy#315]
my code:
    
    
    from flask import Flask
    from flask.ext.sqlalchemy import SQLAlchemy
    from flask.ext.script import Manager,Shell
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:123456@127.0.0.1/hello'
    manager = Manager(app)
    db = SQLAlchemy(app)
    
    class User(db.Model):
        __tablename__ = 'users'
        id = db.Column(db.Integer, primary_key=True)
        username = db.Column(db.String(64), unique=True)
    
    
        def __repr__(self):
            return '<User %r>' % self.username
    
    def make_shell_context():
        return dict(app=app,db=db,User=User)
    manager.add_command('shell',Shell(make_context=make_shell_context))
    
    if __name__ == '__main__':
        manager.run()

I can commit data to database table 

before I commit
mysql> select * from users;
+------+-------------+---------+
| id   | username    | role_id |
+------+-------------+---------+
| NULL | yzxu        |    NULL |
| NULL | dayiguizhen |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | test        |    NULL |
+------+-------------+---------+
13 rows in set (0.00 sec)

then ,I commit it

    yzxu@ubuntu:~/py/github$ python sql.py shell
    
    >>> user = User(username='after')
    >>> db.session.add(user)
    >>> db.session.commit()

after commit data
mysql> select * from users;
+------+-------------+---------+
| id   | username    | role_id |
+------+-------------+---------+
| NULL | yzxu        |    NULL |
| NULL | dayiguizhen |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | yzxu        |    NULL |
| NULL | test        |    NULL |
| NULL | after       |    NULL |
+------+-------------+---------+
14 rows in set (0.00 sec)

but it couldn't return me query
    
    >>> User.query.filter_by(username='after').all()
    [None]

What's wrong with my code?

**Comment by davidism** [comment]
Is that your entire `User` model?  I can't reproduce your issue.

**Comment by dayiguizhen** [comment]
Yes.I just wrote a demo to test use mysql instead of SQLite in flask.
And I try two URI again.
    
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:123456@127.0.0.1/hello'
    #app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')

When I use SQLite URI it returns query
    
    db.create_all()
    >>> u = User(username='yzxu')
    >>> db.session.add(u)
    >>> db.session.commit()
    >>> User.query.all()
    [<User u'yzxu'>]
    >>> quit()

But when I use mysql URI it return None.
    
    >>> User.query.all()
    [None]
    >>> u = User(username='jack')
    >>> db.session.add(u)
    >>> db.session.commit()
    >>> User.query.all()
    [None]
    >>>

Why it can commit succeed but return None?(My Engilsh is poor.So I hope I can describe the trouble I've met clearly)

**Comment by dayiguizhen** [comment]
I found the fault. The table users was created manually by my self without ORM tools, which result in the missing of primary key set on the column id.
