### ISSUE TITLE
Is there anyway to specify constructor when make_declarative_base?

### ISSUE THREAD

**Issue by sungitly** [mitsuhiko/flask-sqlalchemy#317]
Currently make_declarative_base use SQLAlchemy default constructor _declarative_constructor. It will throw TypeError if passed dict parameters contains non-existed model attributes which is not good for me.  Is there anyway I can use my customised constructor instead the default one?

Thanks.

**Comment by davidism** [comment]
Yes, subclass `SQLAlchemy` and override the `make_declarative_base` method with your own version.

**Comment by sungitly** [comment]
well, make_declarative_base method in flask_sqlalchemy uses _BoundDeclarativeMeta and _QueryProperty. If I override make_declarative_base, I have to either import these two private classes or write my own ones.

**Comment by davidism** [comment]
Yes.

**Comment by sungitly** [comment]
Thanks.
