### ISSUE TITLE
cannot run SQLAlchemy

### ISSUE THREAD

**Issue by shantanoo-desai** [mitsuhiko/flask-sqlalchemy#325]
Hello, 
I am trying to run a script to add users to a database. and every time I run the script the error runs into not being able to identify the module. 
the script is from [Bull](https://github.com/jeffknupp/bull) in the *scripts/create_user.py* for my application

my **__init__.py** file is below:
```
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask.ext.bcrypt import Bcrypt
from flask.ext.login import LoginManager


app=Flask(__name__)
# from config.py enabling CSRF for WTForms
app.config.from_object('config')
# database
db = SQLAlchemy(app)
db.init_app(app)

#password hashing
bcrypt = Bcrypt(app)
# login manager
login_manager=LoginManager()
login_manager.init_app(app)

from App import views, models
```

I have tried the following to install 
<pre>
$ flask/bin/pip install Flask-SQLAlchemy
</pre>
also 
<pre>
$ flask/bin/pip install flask-sqlalchemy
</pre>
and I even tried it using `pip install` using the virtual environment. 
the error is :
```
App/__init__.py", line 3, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy

```
I also changed the **flask_sqlalchemy** to the old style of **flask.ext.sqlalchemy** which pops the same error. 

Ironically when I run the shell and try adding user or password and do a 
```
db.session.add(something)
db.session.commit()
```
the code gets executed, without an error.

Where am I going wrong at this? Please help.

Thanks

**Comment by shantanoo-desai** [comment]
Somehow in my root directory I used the `$ pip install flask-sqlalchemy` again and the think is working now.

**Comment by rishits85** [comment]
I am having the same issue on windows. Not sure what is the reason.

**Comment by connelevalsam** [comment]
`sudo pip install flask-sqlalchemy`
solves this issue

**Comment by ThiefMaster** [comment]
never use sudo with pip! always use virtualenvs.

**Comment by connelevalsam** [comment]
i did it without sudo in virtualenvs and it didn't work. After lot's of struggle, sudo worked!

**Comment by theblindguidedog** [comment]
I'm having the same issue and nothing I do fixes it. I've tried everything.
