### ISSUE TITLE
Outdated doc

### ISSUE THREAD

**Issue by andresmrm** [mitsuhiko/flask-sqlalchemy#331]
Hello, the doc here seems outdated:
https://pythonhosted.org/Flask-SQLAlchemy/contexts.html

It says `with app():`, when the correct is `with app.app_context():`, as stated here:
https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/docs/contexts.rst

Just making sure it doesn't go unnoticed.

**Comment by davidism** [comment]
duplicate of #218

**Comment by immunda** [comment]
Yep, bit of a pain.
