### ISSUE TITLE
Want to use the database from Celery

### ISSUE THREAD

**Issue by minhoryang** [mitsuhiko/flask-sqlalchemy#332]
First, really thanks to all for giving me this awesome library.
Now I have a problem when I tried to pull slow-function out to Celery(Asynchronous task runner).

I got the db connection like this:
```python
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'
db = SQLAlchemy()
db.init_app(app)
```

I got the class like this:
```python
class User(db.Model):
    idx = db.Column(db.Integer, primary_key=True)
```

I got the slow function which I want to pull out asynchronously.
```python
@app.route('/slow/<integer:idx>')
def web(idx):
    return slow(idx)

# TODO: Celery Task!
def slow(idx):
    return User.query.get(idx)
```

When I tried to call this directly, I got this message:
```python
RuntimeError: application not registered on db instance and no application bound to current context
```
Is there any way to pull out the 'slow' function outside of Flask?

Please help me to find out the keyword which I can look out or the way to solve this problem.
Thanks :)

**Comment by justanr** [comment]
This is more appropriate for a forum like StackOverflow or reddit.com/r/flask. That said, you need to create a custom task that receives the application as an instance argument, and in the `__call__` method provides an application context. [Here's an example](https://github.com/mattupstate/overholt/blob/e03209f7a059d165a9154355d090738af3159028/overholt/factory.py#L57)

**Comment by minhoryang** [comment]
@justanr Thank you I'll read that code and understand how it works! thanks again!
