### ISSUE TITLE
how to disable cache?

### ISSUE THREAD

**Issue by 1905** [mitsuhiko/flask-sqlalchemy#334]
Hi!
I love flask-sqlalchemy but was forced to use plan sqlalchemy sessions because of this issue:

Initing in my flask app as 
`db = SQLAlchemy(app)`

When I use Model.query.filter_by(id=1).first() I got result, thats ok. But when another app changes DB and there is a change in the table (some rows was changed) - my request will still give me old row!

Am I doing it wrong?

Now I'm using alchemy like this
`session = Session()`
`models = session.query(Model).filter_by(id=1).all()`
`session.close()`

**Comment by davidism** [comment]
I can't reproduce your issue.  I have multiple instances of an app accessing the same database just fine.  Perhaps it is something in you database configuration.  See the SQLAlchemy docs on [Setting Transaction Isolation Levels][1].

[1]: http://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#setting-transaction-isolation-levels

**Comment by immunda** [comment]
Closin'

**Comment by 1905** [comment]
Thank you!
I had and issue described here http://stackoverflow.com/questions/25024302/isolation-level-with-flask-sqlalchemy

**Comment by raushan-itilite** [comment]
facing the same issue
