### ISSUE TITLE
No migration created for altering column from String to Text

### ISSUE THREAD

**Issue by alison985** [mitsuhiko/flask-sqlalchemy#337]
Hi,

I had some columns that I had originally declared db.String(5000) but ran out of space and needed to make them db.Text() fields. I ran `python manage.py db migrate` and `python manage.py db upgrade` and both ran successfully, but I continued getting the 5000 character limit warning. Turns out the migrations that were created (I'm using cookiecutter-Flask) has the upgrade and downgrade functions populated with the word `pass`.

Please let me know if any other information would be helpful in addressing this issue.

Thanks,
Alison

**Comment by davidism** [comment]
https://alembic.readthedocs.org/en/latest/autogenerate.html#comparing-types
