### ISSUE TITLE
``get_debug_queries()`` always returns an empty list ``[]``

### ISSUE THREAD

**Issue by kxxoling** [mitsuhiko/flask-sqlalchemy#338]
I'm using Flask-Debugtoolbar which is using Flask-SQLAlchemy ``get_debug_queries()`` to profile Flask apps. I found it is always 0 query all the time.

Firstly I thought it's something wrong with Flask-Debugtoolbar, but with logging, I found Flask-SQLAlchemy ``get_debug_queries()`` always returns ``[]``.

Then I tried it with my model:

```py
In [29]: with app.app_context():
   ....:     db.create_all()
   ....:     User(name='test', username='uniq').save()
   ....:     print get_debug_queries()
   ....:
[]
```

``User`` is defined:

```py
class SessionMixin(object):
    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def delete(self):
        db.session.delete(self)
        db.session.commit()
        return self

class User(db.Model, SessionMixin):
    __tablename__ = 'users'

    username = db.Column(db.String(50), unique=True)
    name = db.Column(db.String(100))
    email = db.Column(db.String(50))
    avatar = db.Column(db.String(50))
    github_id = db.Column(db.String(20), unique=True)
    github_username = db.Column(db.String(50))
    role = db.Column(db.Integer)

    sighs = db.relationship('Sigh')
    tags = db.relationship('Tag')
    comments = db.relationship('Comment')
```

The version of SQLAlchemy and Flask-SQLAlchemy is the newest version till now.

Both ``SQLALCHEMY_RECORD_QUERIES`` and ``DEBUG`` are set to be true.

**Comment by kxxoling** [comment]
I tried to write a minimal demo for this issue:

```py
from flask.ext.sqlalchemy import get_debug_queries
from wsgi import application as app
from sigh.models import User, db
from flask import current_app

app.debug = True
app.config.update(dict(
    SQLALCHEMY_DATABASE_URI='sqlite:///db.sqlite3' + '?check_same_thread=False'
))

with app.app_context() as ctx:
    print 'sqlalchemy_queries' in dir(ctx)
    user = User(name='Kane').save()
    print 'sqlalchemy_queries' in dir(ctx)
    print get_debug_queries()
```

But ``get_debug_queries()`` works fine here. The output looks like:

```
False
True
[query<balabala...>]
```

But it doesn't work when I use it in view like:

```py
@route('/')
def home():
    users = User.query.all()
    print get_debug_queries()
    return render_template('index.html', users=users)
# Result is []
```

How can I find this issue out?

**Comment by kxxoling** [comment]
I work out a simple demo:

```py
from flask.ext.sqlalchemy import get_debug_queries
from wsgi import application as app
from sigh.models import User, db
from flask import current_app


app.debug = True
app.config.update(dict(
    # SQLALCHEMY_DATABASE_URI='sqlite:///:memory:/ + '?check_same_thread=False' # This works
    # SQLALCHEMY_DATABASE_URI='sqlite:///db.sqlite3' + '?check_same_thread=False' # This works
    # SQLALCHEMY_DATABASE_URI='sqlite:////tmp/db.sqlite3' + '?check_same_thread=False' # Works too
    SQLALCHEMY_DATABASE_URI='sqlite:////Users/windrunner/sigh/db.sqlite3' + '?check_same_thread=False' # Empty list!
))

with app.app_context() as ctx:
    print 'sqlalchemy_queries' in dir(ctx)
    user = User(name='Kane').save()
    print 'sqlalchemy_queries' in dir(ctx)

    print get_debug_queries()
```

It turns out:

```py
False
False
[]
```

**Comment by davidism** [comment]
Please include how `app` and `db` are initialized.

**Comment by kxxoling** [comment]
@davidism Source code here: https://github.com/kxxoling/Programmer-Sign/
I defined ``create_app`` in apps.py, and initialized it in wsgi.py.
``db`` is defined in models.py, and initialized when in ``create_app`` when app is created.

Because config in defined in config.py, and I updated lately, this may have something effect on it.

**Comment by iurisilvio** [comment]
The extension do the instrumentation for debugging purposes on `init_app`. You set the `app.debug` in  `runserver` function.

**Comment by immunda** [comment]
Did @iurisilvio's suggestion resolve this @kxxoling ?

**Comment by kxxoling** [comment]
@immunda Unfortunately no... I defined ``debug=True`` everywhere in my code, and also logged it while serving web request, which is ``True`` as expected.

**Comment by kxxoling** [comment]
I found it works when I set ``SQLALCHEMY_ECHO=True`` which is not what pretended.

**Comment by davidism** [comment]
Here is a minimal example (no external dependencies) which demonstrates the issue.

~~~python3
from flask import Flask
from flask_sqlalchemy import SQLAlchemy, get_debug_queries

SQLALCHEMY_DATABASE_URI = 'sqlite://'

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_object(__name__)
    db.init_app(app)

    with app.app_context():
        db.create_all()

    return app

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)

app = create_app()
app.debug = True

with app.app_context():
    user = User(name='davidism')
    db.session.add(user)
    db.session.commit()
    print(get_debug_queries())
~~~

Note that the engine is initialized because `db.create_all` is called, then `app.debug` is set.  This could be fixed by always registering the debug event on the engine, but exiting early if `app.debug` is `False`, but we're trying to move away from registering events unconditionally for performance.

I'm not willing to change this to support the case where you change config after using the app; config should be done before the app is used.  If you need to change `app.debug` after accessing `db.engine`, you can manually register the events:

~~~python3
app.debug = True
_EngineDebuggingSignalEvents(db.get_engine(app), app.import_name).register()
~~~
