### ISSUE TITLE
BaseModel constructor is not documented

### ISSUE THREAD

**Issue by p-vital** [mitsuhiko/flask-sqlalchemy#341]
https://pythonhosted.org/Flask-SQLAlchemy/api.html#flask.ext.sqlalchemy.BaseQuery has no documentation for BaseModel constructor. This:

-    makes it unclear how to write BaseQuery derivative classes
-    makes it unclear how to instantiate BaseQuery or derived class instances

**Comment by davidism** [comment]
I'm not exactly clear what you're asking for, but I've cleaned up the docs for `BaseQuery` and `Model`.  Typically, you don't instantiate these things yourself, although you can subclass both of them just like normal classes.
