### ISSUE TITLE
Binds parameter not respected

### ISSUE THREAD

**Issue by mattupstate** [mitsuhiko/flask-sqlalchemy#345]
Unfortunately ac135c674fb2d4ae49395e15283be155e826b3ea introduces a bug where one might want to specify an empty dictionary for the `binds` parameter since `{}` is falsey in Python. To get around it for now I was able to do this:

```python
class _dict(dict):
    def __nonzero__(self):
        return True

connection = db.engine.connect()
transaction = connection.begin()
options = dict(bind=connection, binds=_dict())
session = db.create_scoped_session(options=options)

**Comment by immunda** [comment]
Gross, my bad. Could you give me a PR with this reverted and a test case @mattupstate ?
