### ISSUE TITLE
what exactly does SQLALCHEMY_TRACK_MODIFICATIONS do?

### ISSUE THREAD

**Issue by rlam3** [mitsuhiko/flask-sqlalchemy#351]
what exactly does SQLALCHEMY_TRACK_MODIFICATIONS do i'm a bit confused as to why this is needed to be set inside my configuration?

is this tracking sqlalchemy? or flask sqlalchemy?

**Comment by davidism** [comment]
http://flask-sqlalchemy.pocoo.org/2.1/signals/

**Comment by jeffwidman** [comment]
For future searchers: 

http://stackoverflow.com/questions/33738467/sqlalchemy-who-needs-sqlalchemy-track-modifications/33790196#33790196

@davidism You understand this issue better than I do, so if I'm incorrect on anything, feel free to edit my answer.

**Comment by rlam3** [comment]
Is there a way for us to detect which 3rd party packages are affected because of this change? 

So far I think one of these is Flask-WhooshAlchemy

**Comment by eduardocampi** [comment]
thanks
