### ISSUE TITLE
Does flask-sqlalchemy play well with 9.4 postgres better or 9.3?

### ISSUE THREAD

**Issue by rlam3** [mitsuhiko/flask-sqlalchemy#352]
Does flask-sqlalchemy play well with 9.4 postgres better or 9.3? 

Also for the latest flask-sqlalchemy... what version of sqlalchemy should we be updating the pip package to? Thanks!

**Comment by immunda** [comment]
Support for Postgres and, specifically, which Postgres features are supported, is up to SQLAlchemy and broadly speaking independent of Flask-SQLAlchemy.

pip will sort the dependencies for you. That said, it's a good idea to keep SQLAlchemy up to date, and Flask-SQLAlchemy certainly plays nicely with the latest SQLAlchemy release.
