### ISSUE TITLE
Googling 'flask-sqlalchemy docs' leads to very outdated https://pythonhosted.org/Flask-SQLAlchemy/ 

### ISSUE THREAD

**Issue by jeffwidman** [mitsuhiko/flask-sqlalchemy#355]
Googling 'flask-sqlalchemy docs' points to the pythonhosted version which is very out of date--lists v1 as the latest.

Not sure of the best way to fix it because I don't understand where the PythonHosted version gets its source... ideally it'd just 301 to the correct docs on pocoo, or a simple link saying 'latest docs are here'

**Comment by immunda** [comment]
Very good point. Unfortunately I can't put a 301 in place, but I've stuck up a meta refresh.
