### ISSUE TITLE
Customize by subclassing or by __init__ args?

### ISSUE THREAD

**Issue by davidism** [mitsuhiko/flask-sqlalchemy#357]
Traditionally, extension objects such as the model and session were customized by subclassing `SQLAlchemy` and overriding methods.  Newer customizations have been accomplished by adding more args to `__init__`.  As it stands:

* customize by subclass:
    * `db.Model` with `make_declarative_base` which uses `_BoundDeclarativeMeta` by default.
    * `db.session` with `make_session` and `make_scoped_session`, with `SignallingSession` by default.
* customize by `__init__` args:
    * session options, including scope function
    * `db.Query` with `query_class`, defaults to `BaseQuery`
    * `db.Model.metadata` with `metadata`, defaults to `None`
    * `db.Model` base class (the base class of the declarative meta) with `model_class`

Either pattern is viable for all points, I don't really mind either way.  What I don't like is the inconsistency.  Half one way, half another, and a bunch of crossover between the two.  We should decide on a customization style and be consistent about it.

**Comment by immunda** [comment]
Really good point. I'm inclined to standardise on customisations as `__init__` args, as it encapsulates complexity within the Flask-SQLAlchemy lib, rather than pushing it down to users who would potentially have to refactor quite a bit of their application in order to start making use of a customisation.

This approach could cause `__init__` methods to become complex and ungainly long term as more customisations are added, but that would seem to me to be a lesser evil.

**Comment by tristanfisher** [comment]
For similar reasons as @immunda, I'm a fan of the `__init__` approach.  Further, and it might not be entirely rational, needing to override methods reminds me of the pure virtual methods of abstract base classes; if there are defaults that are functional, I think specifying changes in default behavior in the initializer is cleaner than just relying on MRO.

**Comment by justanr** [comment]
I think there's a good argument for both styles. While some things like specifying a query or model class can only really be implemented by altering `SQLAlchemy.__init__`, other things could be handled by introducing or encouraging subclassing.

I'd say if it's a specialization, use a subclass. If it broadens use, change `__init__`. But that's me.

**Comment by immunda** [comment]
Further input on this from other folks?

**Comment by davidism** [comment]
There's one other pattern, which off the top of my head I know Flask-Login uses: class variables and decorator methods on the extension object.  If you want to override something, you either assign it to the extension, or decorate it with a method.  That could be interesting to explore as well.

**Comment by justanr** [comment]
@davidism Something like:

```python
@db.something
def do_the_stuff(...):
    ...
```

I've used this pattern in Flask-Transfer and found it very handy for callbacks.

**Comment by jeffwidman** [comment]
Customizing most of this via `__init__` args feels like the simplest solution to me.

**Comment by immunda** [comment]
Seems like we're settling on `__init__` args, @davidism given you raised this, any objection if we call that consensus?

**Comment by immunda** [comment]
I'm calling it! `__init__` it is 😁
