### ISSUE TITLE
SQLALCHEMY_BINDS parameter is not respected

### ISSUE THREAD

**Issue by deepanshumehndiratta** [mitsuhiko/flask-sqlalchemy#359]
Sample code:

```
from flask import Flask, make_response
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.config['SQLALCHEMY_BINDS'] = {
    'sample1': 'mysql://root:@localhost/sample1',
    'sample2': 'mysql://root:@localhost/sample2'
}

db1 = SQLAlchemy(app)
db2 = SQLAlchemy(app)

@app.route('/')
def home():
	return make_response(str({"db": str(db1.engine)}))

app.run(debug=True)

```

Output:

```{'db': 'Engine(sqlite://)'}```

Whereas, the expected output should bind it to a particular MySQL engine as specified in the SQLALCHEMY_BINDS variable.

Version info:

 - Flask-SQLAlchemy (2.1)
 - MySQL-python (1.2.5)
 - SQLAlchemy (1.0.9)
 - Flask (0.10.1)

**Comment by davidism** [comment]
`SQLALCHEMY_BINDS` specifies extra engines.  The main engine is configured with `SQLALCHEMY_DATABASE_URI`.  You didn't configure that, so it defaults to an in-memory SQLite database.

**Comment by deepanshumehndiratta** [comment]
After specifying ```SQLALCHEMY_DATABASE_URI```, ```db2.get_binds()``` returns ```{}``` and any query on a db2 model with ```__bind_key___ = sample2``` set defaults to db1, where it fails.

**Comment by davidism** [comment]
The following demonstrates how to use multiple binds and introspect them.

~~~python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

SQLALCHEMY_DATABASE_URI = 'sqlite:///db1.db'
SQLALCHEMY_BINDS = {
    'db2': 'sqlite:///db2.db',
    'db3': 'sqlite:///db3.db'
}

app = Flask(__name__)
app.config.from_object(__name__)
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)

class RemoteUser(db.Model):
    __bind_key__ = 'db3'
    id = db.Column(db.Integer, primary_key=True)

print(db.get_engine(app, 'db2'))  # will show sqlite db2.db
print(db.get_tables_for_bind('db3'))  # will show remote_user table
print(db.get_binds(app))  # a dict mapping tables to their bound engine
~~~

**Comment by MaJuanWH** [comment]
Hi I want to know how to do add action if I have create db models.
Can use db.session.add() to bind db?
