### ISSUE TITLE
Documentation for index with multiple keys

### ISSUE THREAD

**Issue by paulohrpinheiro** [mitsuhiko/flask-sqlalchemy#361]
Hi!

You could include a quick explanation of how to create indexes with multiple keys? In SQLAlchemy documentation there is a good application, but for someone like me who have no experience with it, it's easier to look at the page for that extension.

What used was``__table_args__` with `sqlalchemy.schema.Index`.

If I indicate where it would be better to place this information, I myself can create a PR.

Thank you!

**Comment by davidism** [comment]
I'd rather not copy over documentation for SQLAlchemy into Flask-SQLAlchemy.  I added paragraph on the front page linking to the SQLAlchemy docs and describing what the Flask-SQLAlchemy docs are.  Many pages of the docs also already include links to relevant SQLAlchemy docs.

d651a700ea1cc6fa22be03ef71f9a437560cdadd
