### ISSUE TITLE
Execute raw sql on a specific bind

### ISSUE THREAD

**Issue by jbouzekri** [mitsuhiko/flask-sqlalchemy#362]
Hi,

I am using 2 connections to 2 different database. On one of them, I would like to execute a raw query.

How can I target a specific bind to get a connection ?

Thanks

Regards

**Comment by davidism** [comment]
`db.get_engine(app, 'my_bind')`

**Comment by jbouzekri** [comment]
@davidism : Is it possible to do it without having to import the current app ?

**Comment by davidism** [comment]
I'll make a change, since there's no reason for it to require that.

**Comment by davidism** [comment]
bd13c5421ec5d8a233f9b3dc9229262af65be1c2

`db.get_engine(bind='my_bind')` now works using the same app lookup as everything else.

**Comment by jbouzekri** [comment]
Nice. Thank you for doing this so quickly. 

But does it break backward compatibility ? As you switch from a positional argument to a keyword one.

**Comment by immunda** [comment]
No, it's still fine to pass an argument through position or kwarg with a default argument defined.

Regardless, I'm happy to have some (minimal and considered) breakage for `3.0` where it's an improvement such as this.

**Comment by jbouzekri** [comment]
ok. Thanks for clarifying that. Do you have an ETA for this new version ?
