### ISSUE TITLE
Use pytest, test dependency versions

### ISSUE THREAD

**Issue by davidism** [mitsuhiko/flask-sqlalchemy#363]
Flask converted, we should too.  They also test at the minimal, current, and development versions of their dependencies.  I don't think we need to go development, but we definitely need to test at SQLAlchemy==0.8.
- [x] convert to pytest
- [x] split tests into multiple files
- [x] add tests at minimal dependencies to tox
- [x] adjust travis to use new test targets

**Comment by davidism** [comment]
added tox/travis envs in #388

**Comment by thrawny** [comment]
Are looking for help with converting to pytest? I would like to help out.

**Comment by davidism** [comment]
@thrawny yes, that would be a big help! Some things I'd like to do:

* split the tests into different files instead of one big one
* use flat functions instead of classes
* use fixtures where appropriate

**Comment by thrawny** [comment]
@davidism Great! Thanks for the input. Will start working on it then.
