### ISSUE TITLE
SQLALCHEMY_TRACK_MODIFICATIONS warning

### ISSUE THREAD

**Issue by johnwheeler** [mitsuhiko/flask-sqlalchemy#365]
I'm running into this warning

```
        if track_modifications is None:
            warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
```

I do as it says and set it to True, but curious, I look at the source and see it has no effect other than turning off the warning

```
        if track_modifications is None or track_modifications:
            _SessionSignalEvents.register(self)
```

Is there a discussion around this overhead? The error message is a bit confusing

**Comment by immunda** [comment]
Basically it's to let you know that if you haven't explicitly set `SQLALCHEMY_TRACK_MODIFICATIONS` to be enabled or disabled, that it will be removed in the next major release.

So, either turn it off now, or decide you do want the behaviour, knowing it will be removed in the next major version, and explicitly enable it.

**Comment by johnwheeler** [comment]
Hi -

I thought about this a little. Do you think the sentence

"Set it to True to suppress this warning."

might encourage developers to set it to True just to get rid of the warning?

Is it worth bothering over something like 

"Set it to True or False explicitly (default value is None)"

I could do a PR

?
Best,
John

**Comment by davidism** [comment]
1ef899fc376b13f541f574ca33b9a295e7774377

**Comment by begueradj** [comment]
As noted by @immunda , this is the right choice I do:
`app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False`

**Comment by njugunanduati** [comment]
@immunda your solution worked. Thanks

**Comment by pau-lo** [comment]
@immunda worked like a charm!!!!  THANKS!
