### ISSUE TITLE
Issue with subscribing to DB events in a separate process

### ISSUE THREAD

**Issue by lukeyeager** [mitsuhiko/flask-sqlalchemy#369]
I want to subscribe to `models_committed` events in my Flask application which may come from external processes. The external process sees the event, but my Flask app doesn't.
```python
@sa.models_committed.connect_via(app)
def on_models_committed(sender, changes):
    for obj, change in changes:
        # Printed in the external process, but not in the Flask app output
        print 'PUBLISH - %s %s' % (change, obj)
```
Can I not subscribe to events which come from a different session?

Full source code: https://github.com/lukeyeager/flask-sqlalchemy-socketio-demo/blob/6cc45a2fb7/main.py

Related issue with more information specific to my demo app: https://github.com/lukeyeager/flask-sqlalchemy-socketio-demo/issues/1

/cc @ThiefMaster - this is what I was talking with you about yesterday on IRC.

**Comment by RonnyPfannschmidt** [comment]
That's per design events in sqlalchemy are localised.

**Comment by lukeyeager** [comment]
> What you are trying to do is impossible. models_committed only works in the same process where the commit comes from (it's not a DB-level notification, it's sqlalchemy after committing to the DB).
@ThiefMaster

**Comment by lukeyeager** [comment]
Got it. Thanks for the quick responses @RonnyPfannschmidt and @ThiefMaster!
