### ISSUE TITLE
Pessimistic disconnection handling

### ISSUE THREAD

**Issue by torotil** [mitsuhiko/flask-sqlalchemy#375]
Whenever a database connection dies while it is in the connection pool (ie. because the database server is restarted), the next query made will throw an exception and most-likely end up in a HTTP 500 for this request. This seems to be by design in SQLAlchemy it's what they call "optimistic disconnection handling". (see [Disconnection handling](http://docs.sqlalchemy.org/en/rel_1_0/core/pooling.html?highlight=reconnect#dealing-with-disconnects) in the documentation).

In the documentation they also provide a way to check the connection before it is used. This has a tiny performance implications but avoids most such errors.

- What is the best way to use "pessimistic disconnection handling" with Flask-SQLAlchemy?
- Should this be built into Flask-SQLAlchemy?
- Should it be the default behavior?

**Comment by davidism** [comment]
Thanks for the effort, but I don't think this needs to be added to Flask-SQLAlchemy.  It's implemented by copy and pasting the recipe from the SQLAlchemy docs, the extension doesn't effect that.  This extension isn't really the place to add various recipes, as that just adds to the amount of code we need to support.

**Comment by torotil** [comment]
Here is recipe that might be useful to others. Who find this issue: https://github.com/moreonion/moflask/blob/master/moflask/flask_sqlalchemy.py
