### ISSUE TITLE
Doc site missing link to PDF download

### ISSUE THREAD

**Issue by vassudanagunta** [mitsuhiko/flask-sqlalchemy#377]
I was able to figure out the link is http://flask-sqlalchemy.pocoo.org/2.1/.latex/Flask-SQLAlchemy.pdf and successfully downloaded it. 

Looking at the source, the intent was clearly to have the link in the sidebar. 

(Don't have a chance to figure out how to make the change myself at the moment. I'll look into it as soon as I can.)

**Comment by davidism** [comment]
You were looking at the latest source.  It's fixed, just not deployed.

**Comment by vassudanagunta** [comment]
@davidism Are you sure? 

I guess I'm confused by the [2.0 doc site](http://flask-sqlalchemy.pocoo.org/2.0/) having no link to the PDF that I could find, though [the PDF is there](http://flask-sqlalchemy.pocoo.org/2.0/.latex/Flask-SQLAlchemy.pdf). 

Likewise the [2.1 doc site](http://flask-sqlalchemy.pocoo.org/2.1/), though the [the PDF is also there](http://flask-sqlalchemy.pocoo.org/2.1/.latex/Flask-SQLAlchemy.pdf).

**Comment by davidism** [comment]
> just not deployed
