### ISSUE TITLE
Use the teardown_request instead of teardown_appcontext

### ISSUE THREAD

**Issue by erdnaxeli** [mitsuhiko/flask-sqlalchemy#379]
Hi,

I use Flask with Gunicorn. And I see on my database idle sessions, but Flask-SQLAlchemy seems to manage match session scope with the request scope, so something is wrong.

Gunicorn use the WSGI Flask interface. Looking at the Flask code (_Flask.wgsi_app_ method), I: can see it does not relate to the app context, only the request context. Consequence: the _shutdown_session_ method of Flask SQLAlchemy is never called.

The solution is to use the _teardown_request_ decorator, wich do the job even with a WSGI server.

Relating to the issue #99 wich introduce the use of _teardown_appcontext_, I can say no. No, in my case, with Gunicorn (but I thing any other WSGI server will have the same behaviour), the app context is not related to the request context.

Or, I am totaly wrong. This is actually possible. I mean, I don't think I am the only one using Flask and Flask-SQLAlchemy with a WSGI server. And if there were pending sessions, someone would have noticed it. But looking at the code of Flask-SQLAlchemy and the Flask WSGI interface, if I am doing something wrong, I don't see what.

**Comment by georgexsh** [comment]
+1 for this

**Comment by georgexsh** [comment]
+1 for this, I have to do this manually to avoid sqlalchemy transaction error to block whole app from using db connection
```
sqlalchemy.exc.InvalidRequestError
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 
...
```

**Comment by georgexsh** [comment]
also I dont get the design behind the choice of `scopefunc`, by default  `scopefunc` is `connection_stack.__ident_func__` which is effectively implemented with `thread.get_ident`, means that app would get same session within same thread, no matter how many app context on the stack, I think `scopefunc = lambda: id(flask_sqlalchemy.connection_stack.top)`is more desirable.

**Comment by davidism** [comment]
I'm going to need an example of how to run Flask in such a way that the same app context is reused for multiple requests (not for multiple request contexts within a single app context or test, but for actual requests). I can't reproduce this error and using the app context should be correct. The app context is for global app state during an interaction (such as a request or cli command).
