### ISSUE TITLE
Cross schema foreign key is not working with __bind_key__ set

### ISSUE THREAD

**Issue by Wendong-Wu** [mitsuhiko/flask-sqlalchemy#383]
In the original sqlalchemy, we can have cross schema foreign key by defining the the key path in the format of `<schema>.<table>.<field>`. However if we define the model with _bind_key_, we are not able to define the ForeignKey in this format. Because it will consider the whole `<schema>.<table>` part as the table name. 

Example code is here

```python
class Parent(db.Model):
    __tablename__ = 'parent_table'
    __bind_key__ = 'adults'

    parent_id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(255))

class Children(db.Model):
    __tablename__ = 'children_table'
    __bind_key__ = 'kids'

    child_id = Column(Integer, primary_key=True, autoincrement=True)
    parent_id = Column(Integer, ForeignKey('adults.parent_table.parent_id'), nullable=False)
    name = Column(String(255))
```

If we are trying to use `create_all` to generate tables, it will fail with error "cannot find table".

**Comment by davidism** [comment]
`__bind_key__` describes which database a table belongs to, not which schema.  You cannot have foreign keys across databases.

**Comment by EpocDotFr** [comment]
I'm encountering the same issue, and using the `schema` table option doesn't help, I still get a `sqlalchemy.exc.NoReferencedTableError:` exception.
