### ISSUE TITLE
Provide a max_per_page parameter for pagination

### ISSUE THREAD

**Issue by dmulter** [mitsuhiko/flask-sqlalchemy#384]
Right now the default for per_page is 20 unless otherwise specified. I also see that the code makes sure it is no larger than the total items.

To prevent a request asking for too many items at once, it would be convenient if Pagination could be initialized with a maximum items per page (max_per_page). Then the supplied per_page value could use the ceil() of total and max_per_page.

**Comment by kalombos** [comment]
#542
