### ISSUE TITLE
Feature: new method to generate pagination Link header

### ISSUE THREAD

**Issue by dmulter** [mitsuhiko/flask-sqlalchemy#385]
A common thing to do nowadays is to generate an HTTP Link header when creating a paginated response. It would be helpful if there was an additional Pagination method to generate this header.

The following code is a function for generating links for "prev" and "next" if available. I would think it makes more sense as a method (maybe called link_header()) in the Pagination query class. In that case, the first parameter can be removed.

```python
def build_link_header(query, base_url, per_page):
    links = ''
    if query.has_prev:
        links += '<{0}?per_page={1}&page={2}>; rel="prev"'.format(base_url, per_page, query.prev_num)
    if query.has_next:
        if links:
            links += ', '
        links += '<{0}?per_page={1}&page={2}>; rel="next"'.format(base_url, per_page, query.next_num)
    if links == '':
        return None
    else:
        return dict(Link=links)
```

When calling this function, it would look like this. As a query method, it would work as query.link_header()

```python
        link_header = build_link_header(query=page_query, base_url=request.base_url, per_page=request.args.get('per_page'))
        return page_query.items, 200, link_header
```

**Comment by davidism** [comment]
I'd rather leave this to be implemented by projects that need it.  Thanks for the suggestion though.
