### ISSUE TITLE
Is it possible to use classic mapping?

### ISSUE THREAD

**Issue by basco-johnkevin** [mitsuhiko/flask-sqlalchemy#386]
SqlAlchemy allows the user to use classic mapping - http://docs.sqlalchemy.org/en/rel_1_0/orm/mapping_styles.html#classical-mappings

But how can I use classic mapping when using flask-sqlalchemy?

**Comment by davidism** [comment]
```python
user = db.Table(...)

class User:
    ...

mapper(User, user)
```
