### ISSUE TITLE
quickstart - can't run program

### ISSUE THREAD

**Issue by LotosikRa** [mitsuhiko/flask-sqlalchemy#392]
I copy-paste from [this](http://flask-sqlalchemy.pocoo.org/2.1/quickstart/#a-minimal-application) this:
`from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)

    def __init__(self, username, email):
        self.username = username
        self.email = email

    def __repr__(self):
        return '<User %r>' % self.username` 
and have this:
![ice_screenshot_20160429-164905](https://cloud.githubusercontent.com/assets/18006909/14917972/566075c2-0e2a-11e6-864c-38a0c1dbdbc1.png)
 What I need to do to fix it?

**Comment by davidism** [comment]
You need to install SQLAlchemy.  If you `pip install flask-sqlalchemy`, it should have installed all dependencies.  That is the only recommended way to install the package.

**Comment by LotosikRa** [comment]
I don't think so:
![ice_screenshot_20160429-172806](https://cloud.githubusercontent.com/assets/18006909/14919122/f203c65a-0e2f-11e6-847d-325b96f5dae7.png)

**Comment by davidism** [comment]
I can't reproduce your issue.  I installed Flask-SQLAlchemy in an environment, pointed PyCharm at that environment, and it imported without error.  This is not a bug with Flask-SQLAlchemy.  Check that you're running with the same environment you installed to (it can be different than the project default).

**Comment by LotosikRa** [comment]
a real problem is simple -  I changed "sqlalchemy.py" name to "sqlalchemy222.py" and it working. Thanks for help, be more watchful.
