### ISSUE TITLE
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed

### ISSUE THREAD

**Issue by LotosikRa** [mitsuhiko/flask-sqlalchemy#395]
my code: (from http://flask-sqlalchemy.pocoo.org/2.1/quickstart/#quickstart )
`
from app import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)

    def __init__(self, username, email):
        self.username = username
        self.email = email

    def __repr__(self):
        return '<User %r>' % self.username

db.create_all()

a = User('admin', 'admin@example.com')
b = User('guest', 'guest@example.com')

db.session.add(a)
db.session.add(b)
db.session.commit()

print(User.query.all())
`

Error:
`sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.email [SQL: 'INSERT INTO user (username, email) VALUES (?, ?)'] [parameters: ('admin', 'admin@example.com')]`

**Comment by suwenkun1126** [comment]
How to solve this problem?
