### ISSUE TITLE
Provide documentation for use of query_class

### ISSUE THREAD

**Issue by augustjd** [mitsuhiko/flask-sqlalchemy#396]
It is far from obvious how to use the new query_class feature. The docs should have examples, both for relationship-specific query classes (with a `relationship()` kwarg) and class-specific query classes (with the query_class attribute).

I've been using Python for a long time and was still a little shaky on whether attributes (like query_class) could be overridden by child classes (they can). Perhaps there are other people in my same boat who would appreciate this getting spelled out in the docs.

Great feature, more people could benefit from knowing how to use it!

**Comment by justanr** [comment]
@immunda I can submit a PR for this since I should've included docs when I added this.

**Comment by immunda** [comment]
Think the new page that you've done in #415 is a good fit @justanr, thanks!
