### ISSUE TITLE
Pool configuration keys default do not match documentation

### ISSUE THREAD

**Issue by yoyoprs** [mitsuhiko/flask-sqlalchemy#397]
I use mysql adapter.

_SQLALCHEMY_POOL_SIZE : The size of the database pool. Defaults to the engine’s default (usually 5)_

This value is **None** by default

_SQLALCHEMY_POOL_TIMEOUT : Specifies the connection timeout for the pool. Defaults to 10._

This value is **None** by default

_SQLALCHEMY_POOL_RECYCLE: Number of seconds after which a connection is automatically recycled. This is required for MySQL, which removes connections after 8 hours idle by default. Note that Flask-SQLAlchemy automatically sets this to 2 hours if MySQL is used._

This value is **None** by default

**Comment by davidism** [comment]
A value of `None` commonly means "something down the line will pick a default", which is what happens here.  They default to `None` in Flask-SQLAlchemy, and are passed directly to SQLAlchemy in `create_engine`, which has these defaults.  (Except for recycle, which, as the docs already say, is handled specially for MySQL.)
