### ISSUE TITLE
provide support for sqlalchemy.ext.automap

### ISSUE THREAD

**Issue by nexero** [mitsuhiko/flask-sqlalchemy#398]
SQLAlchemy's automapper provides reflection of an existing database and it's relations.

**Comment by jsangilve** [comment]
@nexero, I think you can use SQLAlchemy's automap doing something like this:
```python
 app = Flask(__name__)
 app.config['SQLALCHEMY_DATABASE_URI'] = 'database_uri'
 db = SQLAlchemy(app)
 metadata = MetaData()
 tables = ['user']
 metadata.reflect(db.engine, only=tables)
 Base = automap_base(metadata=metadata)
 Base.prepare(name_for_scalar_relationship=name_for_scalar_relationship,
              name_for_collection_relationship=name_for_collection_relationship)

@app.route('/test')
def test_request():
    User = Base.classes.user
    usr = db.session.query(User).filter_by(username='nexero').first()
    return usr.username
```

**Comment by davidism** [comment]
You can also subclass the extension class and implement your own declarative base.  We're not planning on adding custom code for every SQLAlchemy feature.  Is there a specific problem you're having using it right now?

**Comment by zmrow** [comment]
When did the automap() functionality get baked into flask-sqlalchemy?  Doesn't appear to be in the changelog.  I'm using 1.0 and it doesn't appear to be in there either.  :)

**Comment by davidism** [comment]
@zmrow  There has never been any special handling of automap in this extension.  See my previous comment.  If the extension is doing something that blocks the use of automap, please open a more specific bug report.

**Comment by zmrow** [comment]
Nevermind.... I see i my SQLAlchemy version was WAAY out of date... Sorry.

**Comment by osya** [comment]
@davidism , in the scope of supporting SQLAlchemy's Automap feature in Flask-SQLAlchemy I suggest to just add `**kwargs` parameter to the methods `reflect()` and `_execute_for_all_tables()` according to the [post](https://stackoverflow.com/a/23298371/1360307). Surely, you can say that anyone can subclass SQLAlchemy class and override these methods. But it is very simple change and it supports multiple possible parameters. Currently I implement such subclass in my code: 
```
class MySQLAlchemy(SQLAlchemy):
    """
        Fixing the issue with missing `only` parameter in the Flask-SQLAlchemy's reflect() method
        Links: 
            - https://stackoverflow.com/questions/23292931/flask-sqlalchemy-views-reflection
            - https://github.com/mitsuhiko/flask-sqlalchemy/issues/398
    """
    def _execute_for_all_tables(self, app, bind, operation, skip_tables=False, **kwargs):
        app = self.get_app(app)

        if bind == '__all__':
            binds = [None] + list(app.config.get('SQLALCHEMY_BINDS') or ())
        elif isinstance(bind, string_types) or bind is None:
            binds = [bind]
        else:
            binds = bind

        for bind in binds:
            extra = {}
            if not skip_tables:
                tables = self.get_tables_for_bind(bind)
                extra['tables'] = tables
            op = getattr(self.Model.metadata, operation)
            op(bind=self.get_engine(app, bind), **extra)

    def reflect(self, bind='__all__', app=None, **kwargs):
        self._execute_for_all_tables(app, bind, 'reflect', skip_tables=True, **kwargs)
```
And this is my code for automap: 
```
injector = Injector()
    FlaskInjector(app=app, injector=injector, modules=binds)
    db = injector.get(SQLAlchemy)
    db.metadata.bind = db.engine
    db.metadata.reflect(only=['resource'])
    from sqlalchemy.ext.automap import automap_base
    base = automap_base(metadata=db.metadata)
    base.prepare()
    resource = base.classes.resource
```
I can prepare PR if you agree
