### ISSUE TITLE
In windows7, make_declarative_base error

### ISSUE THREAD

**Issue by fivejjs** [mitsuhiko/flask-sqlalchemy#405]
On line 741 in **init**.py, error message: positional argument 1 but 2 given.

I replace the line with the following snippet. It works.

```
    try:
            if metadata:
                self.Model = self.make_declarative_base(metadata)
            else:
                self.Model = self.make_declarative_base()
        except:
            pdb.set_trace()
```

**Comment by immunda** [comment]
`make_declarative_base` has a default argument of `None` for `metadata` so I'm not sure I follow.

Can you please explain the context and what it also has with Windows 7.
