### ISSUE TITLE
Oracle: Identifier Name too long

### ISSUE THREAD

**Issue by cemremengu** [mitsuhiko/flask-sqlalchemy#411]
When selecting from an Oracle database, alchemy uses identifier names which cause `identifier too long errors` 

Is there way to prevent this maybe by disabling using identifiers ?

```
DataType.query.with_entities(DataType.type)


SELECT "MY_SCHEMA"."POC_TURK_DATA_TYPES".type AS "MY_SCHEMA_POC_TURK_DATA_TYPES_type"                                                                                           
FROM "MY_SCHEMA"."POC_TURK_DATA_TYPES"   
```

` "MY_SCHEMA_POC_TURK_DATA_TYPES_type" ` is causing the error (longer than 30 chars)

**Comment by davidism** [comment]
This is a SQLAlchemy issue, not Flask-SQLAlchemy.
