### ISSUE TITLE
SQLAlchemy.init_app doesn't sets self.app

### ISSUE THREAD

**Issue by CTACyok** [mitsuhiko/flask-sqlalchemy#414]
SQLAlchemy::init_app doesn't set `self.app = app`, which causes problems with delayed app initialization when Flask-Restless extension calls SQLAlchemy::get_app
Was it intentional?

**Comment by davidism** [comment]
https://github.com/mitsuhiko/flask-sqlalchemy/search?utf8=%E2%9C%93&q=init_app+is%3Aclosed&type=Issues
