### ISSUE TITLE
Auto increment SQLite 3

### ISSUE THREAD

**Issue by johndiego** [mitsuhiko/flask-sqlalchemy#419]
How can i make table with auto_increm?
My code

```
class Filedb(db.Model):
    __table_args__ = {'sqlite_autoincrement': True}
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
 ```
thanks.

**Comment by davidism** [comment]
~~~python
class Filedb(db.Model):
    id = db.Column(db.Integer, primary_key=True)
~~~

should be all you need.  Note that nothing here is specific to Flask-SQLAlchemy.  Please use the issue tracker only for reporting bugs in the library itself.
