### ISSUE TITLE
enquiry : multi tenant

### ISSUE THREAD

**Issue by mikekitur** [mitsuhiko/flask-sqlalchemy#420]
hi all,

i am new on the python/flask-sqlalchemy. has been researching the internet, but didnt find any sample that somebody do this with flask-sqlachemy. i will appreciate if you can point me to the direction also. 

i am developing rest api, that will return result from different database schema based on userid.
e.g. userid = 1, db schema = tenant1. 
       userid = 2 , db schema = 2.

understand that currently flask-sqlalchemy allow multi database with binding. but are we allow to add binding configurable in database?

What i mean is something like this.

1. store the userid and db mapping in database table. [common table for all tenants]
    userid = 1, db schema = tenant1. 
    userid = 2 , db schema = tenant2 

2. when somebody run a query on the rest api by passing userid, i will use pymysql connectiong (with sqlalchemy) to retrieve the schema and then bind the schema accordingly to the URI. 
   e.g app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:root@localhost/' + [tenant based on userid]

3. i have done point 1 and 2, but once the schema is bind, i am not able to switch schema.
   what i mean is that if userid =1 have first query the rest api, the rest api will always bind to tenant1.
   even though i change the URI to "tenant2",
         app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:root@localhost/' + tenant2
   the query will still return the data in tenant1.

is it possible to be done in flask-sqlalchemy?

Many thanks in advance.
Thanks

**Comment by Zengdewei1** [comment]
I have the same question as you. Did you solve this problem?
