### ISSUE TITLE
issue warning if SQLALCHEMY_DATABASE_URI is not set

### ISSUE THREAD

**Issue by scotchka** [mitsuhiko/flask-sqlalchemy#421]
Currently, if the user misspells SQLALCHEMY_DATABASE_URI, say, as SQLALCHEMY_DATABASE_URL, the database defaults to SQLite which is usually not the intended database. It would be better to raise a UserWarning that makes clear the the app is defaulting to SQLite.

Any reason to not issue such a warning? If not, I can make the pull request.

**Comment by kingsj0405** [comment]
I really agree with this issue... I spent over 5 hours realizing URI not URL...
