### ISSUE TITLE
My MySQL database connection timeout 

### ISSUE THREAD

**Issue by Pinsonbavard** [mitsuhiko/flask-sqlalchemy#423]
Hi guys,

I dont know why my MySQL database connection timeout and I have to reload the page every time before it comes up.

The problem did not go away even after setting the properties

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_POOL_SIZE'] = 100
app.config["SQLALCHEMY_POOL_RECYCLE"] = 280

I have a Flask app connecting to an external MySQL database on another server. But the database connections closes it connection after some minutes and I have to reload the page multiple times or I get an Internal server error in the application.

**Comment by davidism** [comment]
Adjust the connection timeout in your database configuration.  Long running requests that hold a connection will be timed out by the database server, not SQLAlchemy.  Pool recycle only applies to opening new connections when they are first acquired.  Please use an appropriate Stack Exchange site for questions about your own code.
