### ISSUE TITLE
Use inflection to produce tablenames

### ISSUE THREAD

**Issue by dusktreader** [mitsuhiko/flask-sqlalchemy#427]
It would be nice if you used the inflection library to generate table names instead of your own regex.

There is already a function called 'tableize' in the inflection package that converts to snake_case and pluralizes the table name.

In any case, it would be nice to be able to either control behavior of the automatic table name generation or override it

**Comment by davidism** [comment]
I'm aware of the library but do not plan to add an external dependency.  We do plan on addressing this.  Duplicate of #406.
