### ISSUE TITLE
lazy="dynamic" as a default parameter should be discouraged

### ISSUE THREAD

**Issue by inklesspen** [mitsuhiko/flask-sqlalchemy#435]
The flask-sqlalchemy docs show using `lazy="dynamic"` in every relationship example, and indeed say "This is usually what you want if you expect more than a handful of items for this relationship."

This is false. Dynamic loading means that every access of the relationship will execute a SQL query, potentially causing performance issues. Additionally, SQLAlchemy docs recommend it as an advanced topic for very large collections, not a default. Dynamic relationships behave sufficiently differently from ordinary relationships and this confuses newcomers to SQLAlchemy.

**Comment by davidism** [comment]
addressed in #459

**Comment by roelzkie15** [comment]
This is correct! man I'm new to flask-sqlalchemy and using the approach caused us to have a latency of 32s in a single request! XD
