### ISSUE TITLE
MySQL server has gone away error using db.session

### ISSUE THREAD

**Issue by dylanjbarth** [mitsuhiko/flask-sqlalchemy#449]
Possibly related: https://github.com/mitsuhiko/flask-sqlalchemy/issues/2 

### the issue
Getting `OperationalError: (OperationalError) (2006, 'MySQL server has gone away')` when I attempt to use `db.session.commit()` with `SQLALCHEMY_POOL_RECYCLE` set to the 2 hour default. On the server, we have the mysql defaults (8 hour `wait_timeout` and `interactive_timeout`).

The expected behavior, unless I am misinterpreting the docs, is that because `pool_recycle` is less than the `wait_timeout`, `flask-sqlalchemy` will reconnect to the DB and this error wouldn't be raised. It's definitely possible I misread something, so opening this here in case anyone can shed some light for me. Raising here instead of stackoverflow because at this point, it feels like a bug. 

### steps to reproduce
To reproduce locally, I set mysql timeouts to 10s, relevant `.my.cnf`: 
```
[mysqld]
wait_timeout = 10
interactive_timeout = 10
```
and updated app settings to: `SQLALCHEMY_POOL_RECYCLE = 3`.

To recreate a situation where the timeout had elapsed, I wrote a test that called an endpoint in our flask app to run essentially this code: 
```python 
def save_record(record):
    import time; time.sleep(11)  # allow mysql to expire our DB connection
    try:
        db.session.add(record)
        db.session.commit()
    except sqlalchemy.exc.ProgrammingError as e
         db.session.rollback()
         raise e        
    return record
```

I injected a breakpoint and in a mysql shell, running `SHOW FULL PROCESSLIST;` was able to see the mysql connection expire, and then the code raise `MySQL server has gone away`. 

However, when I exchange `db.session` for some engine call, say `db.engine.execute("SELECT * from records")`, I see that a connection is created and a result proxy instance is returned. 

Looking through the code, I see that the `pool_recycle` option is being applied to `db.engine` which is getting passed to `SessionBase` in the `__init__` of `SignallingSession`, so I'm confused as to why a new connection isn't being created for the session.

**Comment by dylanjbarth** [comment]
Ignore me, sorry, my test actually isn't properly reproducing what I saw in production. Closing this for now, will re-open when/if I can properly reproduce.

**Comment by dylanjbarth** [comment]
I haven't been able to reproduce locally, but we hit this in production again, so I'm re-opening in case somebody can shed some light. 

The issue is the same: 

> Getting OperationalError: (OperationalError) (2006, 'MySQL server has gone away') when I attempt to use db.session.commit() with SQLALCHEMY_POOL_RECYCLE set to the 2 hour default. On the server, we have the mysql defaults (8 hour wait_timeout and interactive_timeout).

> The expected behavior, unless I am misinterpreting the docs, is that because pool_recycle is less than the wait_timeout, flask-sqlalchemy will reconnect to the DB and this error wouldn't be raised. It's definitely possible I misread something, so opening this here in case anyone can shed some light for me. Raising here instead of stackoverflow because at this point, it feels like a bug.

**Comment by davidism** [comment]
From the SQLAlchemy [docs](https://docs.sqlalchemy.org/en/latest/core/pooling.html#dealing-with-disconnects):

> Note that the invalidation **only** occurs during checkout - not on any connections that are held in a checked out state.

If you're already using the session, the connection was checked out at the beginning. The `recycle` parameter will only affect the next connection. So if you acquire a connection and it times out, it will raise an exception. Executing from the engine uses a separate connection from the session.  You can examine the state of the pool by enabling `db.engine.pool.echo` or by calling `db.engine.pool.status()`.

I can't really tell if your small example actually represents the same problem you're having in production, and it's not really a self-contained example so it's hard to recreate on my end. If this actually is your issue, then something is holding a connection open for more than the timeout then attempting to use it. This is probably out of Flask-SQLAlchemy's control anyway, as connections are handled by SQLAlchemy and MySQL.

**Comment by lizzywang** [comment]
Hi I encounter the same problem. However the endpoint of my webapp won't hit this error. The background scheduler will sometimes hit this error.
