### ISSUE TITLE
SQLAlchemy.__repr__ displays db user and db password

### ISSUE THREAD

**Issue by robkorv** [mitsuhiko/flask-sqlalchemy#455]
Is there a way to hide this?

**Comment by robkorv** [comment]
I just noticed that the `repr` of `sqlalchemy.engine.url.URL` hides the db password.
@mitsuhiko are you interested in a pr  that hides the db password in the `SQLAlchemy.__repr__` by default?

**Comment by mitsuhiko** [comment]
Yeah, sounds like a good patch.

**Comment by davidism** [comment]
1898df5dd9e21a93dd694c3ac57153df9ea24264
