### ISSUE TITLE
string primary key

### ISSUE THREAD

**Issue by Paul-Darius** [mitsuhiko/flask-sqlalchemy#457]
Hi!
When I try to create a model from an existing postgreSQL database, with a primary key being of string type as shown here:
```
class Stuff(db.Model):
    __tablename__ = 'stuff'
    stuff1 = db.Column(db.String(100), primary_key = True),
    stuff2 = db.Column(db.String(1000)),
    stuff3 = db.Column(db.String(1000))

    def __init__(self, stuff1, stuff2, stuff3):
        self.stuff1 = stuff1
        self.stuff2 = stuff2
        self.stuff3 = stuff3

    def __repr__(self):
        return '<Stuff %r>' % self.stuff1
```

The soft return `Mapper Mapper|Stuff|stuff could not assemble any primary key columns for mapped table 'stuff'`

It works just fine with the same database + an id column of integer type as a primary key instead.
Is there any particular reason it does not work?

Thanks a lot.

**Comment by davidism** [comment]
You have a typo: remove the comma at the end of the `stuff1 = ` line.

**Comment by codeguru42** [comment]
And after the `stuff2 = ...` line, too

**Comment by Paul-Darius** [comment]
It was quite obvious, I am really sorry, thank you very much!
