### ISSUE TITLE
Why Flask-SqlAlchemy instead of pure SqlAlchemy?

### ISSUE THREAD

**Issue by theobouwman** [mitsuhiko/flask-sqlalchemy#463]
Why should I use this module instead of the pure sqlalchemy?

**Comment by davidism** [comment]
Literally the first paragraph in the docs:

> Flask-SQLAlchemy is an extension for Flask that adds support for SQLAlchemy to your application. It aims to simplify using SQLAlchemy with Flask by providing useful defaults and extra helpers that make it easier to accomplish common tasks.

There's nothing stopping you from using SQLAlchemy yourself, you'll just have to do something similar to what the extension does for setup anyway.
