### ISSUE TITLE
How about let tablename prefix configable?

### ISSUE THREAD

**Issue by protream** [mitsuhiko/flask-sqlalchemy#464]
Add a configuration option, like `SQLALCHEMY_TABLENAME_PREFIX`.

**Comment by davidism** [comment]
Why? I'm going to say no, if you need this you can still customize things however you want. The tablename stuff is already complex enough.

**Comment by protream** [comment]
@davidism 
I tried to use `declared_attr`, but not work. #323 has reported this issue. I think override `make_declarative_base` is a little weird and complecated to a beginner like me.

**Comment by davidism** [comment]
Subclassing is a standard part of Python and a normal way to extend Flask and its extensions.
