### ISSUE TITLE
MySQL timeout on LONG running requests.

### ISSUE THREAD

**Issue by reiinakano** [mitsuhiko/flask-sqlalchemy#465]
I have a web application using Flask-SQLAlchemy and celery to process very long-running tasks. I wrap the Celery object using this code snippet (http://flask.pocoo.org/docs/0.12/patterns/celery/) in order to run the celery task inside the Flask application context. The problem is when a celery task (that needs to write to the database) takes more than 8 hours, MySQL closes the connection and I get the error 'MySQL Server has gone away'. I've searched around and so far I could not see what the best way is to reopen the DB session from the Flask-SQLAlchemy + Celery task level and thought the best way to handle this would be in the Flask-SQLAlchemy level.

Here's a simplified view of my `tasks.py`:
```python
from application import db # db is the Flask-sqlalchemy db object
from application.celery import celery 
from application.models import DBModel

@celery.task(acks_late=True, bind=True)
def long_task(self):
    my_db_model = DBModel.query.filter_by(param="param").first()
    sleep(93014903249)
    my_db_model.param = "newparam"
    db.session.add(my_db_model)
    db.session.commit()
```

If there is a simple bandaid fix to this I would love to know about it. I haven't delved too deep into the Flask SQLAlchemy source code yet so I'm a bit clueless..

**Comment by pkaczynski** [comment]
Have you tried setting connect_timeout and wait_timeout to higher values in your mysql config?

**Comment by reiinakano** [comment]
Hi, I don't think I want to resort to something like that as I wouldn't know what to set it to either. The tasks can take even weeks in extreme cases. Having some way to reset the connection during the task would be helpful.

**Comment by chribsen** [comment]
For MySQL you'll need to specify `SQLALCHEMY_POOL_RECYCLE ` which defaults to 8 hours.
The [docs]( http://flask-sqlalchemy.pocoo.org/2.1/config/) says:

> Number of seconds after which a connection is automatically recycled. This is required for MySQL, which removes connections after 8 hours idle by default.


Also.. It sounds like a rather extreme use of Celery tasks. You should think about parallelizing the job into multiple tasks and maintaining a connection pool.

**Comment by davidism** [comment]
At this point, it doesn't sound like a Flask-SQLAlchemy bug. Please use the mailing list for discussions.
