### ISSUE TITLE
Overwrite of pool_size and pool_recycle on apply_driver_hacks for mysql driver

### ISSUE THREAD

**Issue by salvorapi** [mitsuhiko/flask-sqlalchemy#466]
When I set `SQLALCHEMY_POOL_SIZE` and `SQLALCHEMY_POOL_RECYCLE` they aren't recognized. I think that the order of `apply_pool_defaults` and `apply_driver_hacks` overrides `pool_size`.

**Comment by davidism** [comment]
Neither of those methods override config, they just set defaults. Please include a minimal example demonstrating your issue.

**Comment by salvorapi** [comment]
This library is included on privacyIDEA product. 
privacyIDEA has a config file called pi.cfg where store config parameter of sqlalchemy.

```
SQLALCHEMY_POOL_SIZE=5
SQLALCHEMY_DATABASE_URI='mysql+mysqldb://pi:pi@127.0.0.1:3306/pi'
SQLALCHEMY_POOL_TIMEOUT=30
SQLALCHEMY_POOL_RECYCLE=10
```

If I set `pool_size` and `pool_recycle` parameter on pi.cfg doesn't work.
But changing that parameter directly in function **apply_driver_hacks** it work.
I think that issue is on `info.drivername != 'mysql+gaerdbms'`

Thank you.

Salvo.

**Comment by davidism** [comment]
> Please include a minimal example demonstrating your issue.

**Comment by salvorapi** [comment]
Ok, I found that this is not my issue.
I think that my problem is with configuration of wsgi application (multi process multi thread).
Sorry, 

Thank you.

Salvo.
