### ISSUE TITLE
how to let flask-sqlalchemy's query object select columns ( or say fields )?

### ISSUE THREAD

**Issue by iceblove** [mitsuhiko/flask-sqlalchemy#47]
hi, Armin,

I met some problem that wired me the whole day. I'm using flask/flask-sqlalchemy/postgresql, and I want to do this:

published_sites = msg_published.query \
            .filter( and_(*filter_clause) ) \
            .group_by( msg_published.site_id ) \
            .order_by( order_clause ) \
            .paginate( page_no, per_page, error_out = False )
but in mysql, it is OK, and in postgresql it is wrong and ask for the other fields besides site_id either in a group by clause or in a aggregation function, I know that postgresql is stricter on SQL than mysql , so I must select the site_id in the query object of msg_published, but in pure sqlalchemy I can do like this:

published_sites = session.query( msg_published.site_id ) \
            .filter( and_(*filter_clause) ) \
            .group_by( msg_published.site_id ) \
            .order_by( order_clause ) \
            .paginate( page_no, per_page, error_out = False )
and in flask-sqlalchemy, how to get it work?

**Comment by DmonteiroD** [comment]
I am having the same question. the supposed result is this?

[(1,), (6,), (8,), (50,), (73,), (74,), (75,), (76,), (77,), (78,), (79,), (80,), (81,), (82,), (83,), (84,), (85,), (86,), (87,)]

How about this?

[1, 6, 8, 50 ... ]

**Comment by bastianh** [comment]
this is not a help forum.. and this is not even an sqlalchemy question but simple python.

try result = [x[0] for x in result]

**Comment by madtune** [comment]
I used mysal 

```
CREATE TABLE "thread" (	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT )
INSERT INTO `thread`(`id`) VALUES (1);
```

Here it's  my DB model
```
class Thread(db.Model):
      id = db.Column(db.Integer, primary_key=True)
```
And code to select any row from database 
```
threads = Thread.query.filter_by(id='1')
```

**Comment by irmscher9** [comment]
Is there a way to make a query without the Model object? Let's say I 've already some data pre-populated in my postgres database?
