### ISSUE TITLE
`InvalidRequestError: Table … is already defined for this MetaData instance` (table inheritance on v2.2)

### ISSUE THREAD

**Issue by homeworkprod** [mitsuhiko/flask-sqlalchemy#478]
On Flask-SQLAlchemy 2.2 (Flask 0.12, SQLAlchemy 1.1.6, Python 3.5.3) I the following traceback that does not occur with Flask-SQLAlchemy 2.1:

```pytb
Traceback (most recent call last):
  File "application.py", line 19, in <module>
    class ChildA(Parent):
  File "/home/user/project/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 602, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "/home/user/project/venv/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/home/user/project/venv/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/user/project/venv/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/user/project/venv/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in __init__
    self._setup_table()
  File "/home/user/project/venv/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 395, in _setup_table
    **table_kw)
  File "/home/user/project/venv/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 418, in __new__
    "existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'items' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

Somewhat minimal code to reproduce:
```py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class Parent(db.Model):
    __tablename__ = 'items'
    __mapper_args__ = {
        'polymorphic_identity': 'parent',
        'polymorphic_on': 'type',
    }

    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.Unicode(10), nullable=False)


class ChildA(Parent):
    __mapper_args__ = {
        'polymorphic_identity': 'child_a',
    }

    foo = db.Column(db.Integer)


class ChildB(Parent):
    __mapper_args__ = {
        'polymorphic_identity': 'child_b',
    }

    bar = db.Column(db.Integer)


app = Flask(__name__)
app.run()
```

Unless I've been doing that wrong the whole time and just got away with it by chance, I think this might be unintended behavior on Flask-SQLAlchemy's side.

**Comment by ThiefMaster** [comment]
See #473 / #470

**Comment by homeworkprod** [comment]
Yeah, read those earlier, but couldn't make a sufficiently clear connection; my example above derives from `db.Model` and doesn't use `@declared_attr`.

**Comment by ThiefMaster** [comment]
I think it's a general problem with polymorphy and the latest changes in Flask-SA. I'd pin the version to 2.1 until this is fixed - I don't think there's any workaround for now

**Comment by homeworkprod** [comment]
Thanks, will do that.

**Comment by davidism** [comment]
To be clear, did you write those models intending single-table or joined-table inheritance? Considering changing the autogeneration logic so that single-table would require you to set `__tablename__ = None`.

**Comment by davidism** [comment]
[This test](https://github.com/mitsuhiko/flask-sqlalchemy/pull/541/files#diff-d9700c2ad593fa698e677376e6458736R117) from #541 should cover this case. Tablenames and tables are not created for single-table inheritance subclasses.

Until 2.3 is released, if you didn't just pin 2.1, you could set `__tablename__ = None` for STI.

**Comment by homeworkprod** [comment]
v2.3.0 seems to have fixed the issue for me, thanks!

**Comment by itsjef** [comment]
Issue is met again in v2.3.1 and v2.3.2. Please take a look!

**Comment by davidism** [comment]
If you have a new issue, please open a new ticket with an example demonstrating it.

**Comment by zaraki02** [comment]
First try db.create_all( )...Trust me it will work, where u created ur models for the database...Happy coding!
