### ISSUE TITLE
`get_app()` in connectors return uncertainty `app`

### ISSUE THREAD

**Issue by lifei** [mitsuhiko/flask-sqlalchemy#490]
`SQLAlchemyState.connectors` hold the app get from `get_app()`. When connectors are created under flask context, theirs `_app` is `current_app`. Otherwise, theirs app is `SQLAlchemy.app`. Connectors created under the second scene work fine without flask context, while those created under the first scene raise exceptions.

Also if connectors have created under the second scene, they are not changed along with the flask context. In this case, the purpose of making `current_app` is not achieved.

**Comment by ThiefMaster** [comment]
If an explicit app is set, this app is always used. This is intentional.

If you want to use the app context, do not pass an app to `SQLAlchemy()` but only use `init_app`.
