### ISSUE TITLE
schema for multiple binds

### ISSUE THREAD

**Issue by itajaja** [mitsuhiko/flask-sqlalchemy#494]
Hi! how can you specify two different postgres schemas with two different binds? And as a more generic question, in the following code: `SQLAlchemy(app).metadata` refers to the default bind, correct? How can we access/modify the other metadata binds?

**Comment by ThiefMaster** [comment]
Schemas have nothing to do with binds (different connections/databases). If you want to use schemas, set it through the table args.

**Comment by itajaja** [comment]
I mean a postgres schema. In my opinion it has to do with a connection though, because if I have two binds (connections). it's likely they are going to access to different schemas. if I do 

```
db = SQLAlchemy(app)
db.metadata.schema = 'foo'
```

the foo schema is used in both connections?

**Comment by ThiefMaster** [comment]
Why set it on the metadata at all?

**Comment by itajaja** [comment]
because it's a great shorthand? otherwise you'd have to set it on every table.

But let's leave the schema thing aside, still there is a one to one relationship between a bind and a metadata object. see http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.MetaData. So the question remains, if you specify multiple binds, what does `SQLAlchemy(app).metadata` returns?

**Comment by davidism** [comment]
Duplicate of #222
