### ISSUE TITLE
[question] Best practice for using ORM in recurring task

### ISSUE THREAD

**Issue by biran0079** [mitsuhiko/flask-sqlalchemy#499]
From my understanding, ORM is backed by a session and it implicitly starts transaction with a db read.
If I want to use ORM in a background thread that runs recurring task that only reads db without calling `session.commit()`, then it may stay in the uncommitted transaction and the read result will stay the same even actual db data are changed (assume db is MySql and isolation level is repeatable read).

What is the best practice for using ORM in such scenario?

**Comment by jpassaro** [comment]
if you surround your recurring task with `with app.app_context():`, i think it should begin a fresh session each time it executes... If I had trouble along these lines, this is the first thing i'd try.

**Comment by davidism** [comment]
http://flask.pocoo.org/docs/0.12/patterns/celery/

Please use IRC or the mailing list for discussions about your own code. This tracker is for issues with Flask-SQLAlchemy's code.
