### ISSUE TITLE
setting db on the fly

### ISSUE THREAD

**Issue by mtung2017** [mitsuhiko/flask-sqlalchemy#504]
Wanted to ask if there is something in the library to let me change the database connection to point to a different db on the fly? The thing I'm trying to do is from a POST request I use the credentials to connect to the database.

**Comment by ThiefMaster** [comment]
No, and I don't think this will ever be added - it would not be able to affect any other processes for example.

**Comment by mtung2017** [comment]
There isn't a way to reset the connection?

**Comment by ThiefMaster** [comment]
No. If you have multiple processes there would be no way of changing it in the other processes.

Also, why do you want to do this?

**Comment by mtung2017** [comment]
I want to be able to have a user tell me what his/her credentials are before I serve that data in flask.

**Comment by ThiefMaster** [comment]
What do the user's credentials have to do with the database connection data?

**Comment by mtung2017** [comment]
user credentials = db connection details. It's data specific to each user's account
