### ISSUE TITLE
Defining your entry point module as "site.py" causes NoAppException

### ISSUE THREAD

**Issue by Kangaroux** [mitsuhiko/flask-sqlalchemy#507]
If you create a file called `site.py` which defines your Flask app, and then set the env var as `FLASK_APP="site.py"`, Flask will find the file but it can't find the application instance. 

```
Traceback (most recent call last):
  File "/asdf/venv/lib/python3.4/site-packages/flask/cli.py", line 48, in find_best_app
    'using a factory function.' % module.__name__)
flask.cli.NoAppException: Failed to find application in module "site".  Are you sure it contains a Flask application?  Maybe you wrapped it in a WSGI middleware or you are using a factory function.
```

Folder structure: http://i.imgur.com/CR88kUo.png

requirements.txt

```
Flask==0.12.1
Flask-SQLAlchemy==2.2
Jinja2==2.9.6
MarkupSafe==1.0
SQLAlchemy==1.1.10
Werkzeug==0.12.1
click==6.7
itsdangerous==0.24
```

**Comment by jpassaro** [comment]
This probably belongs in pallets/flask, I can repro without flask-sqlalchemy.

The `flask run` command works by transforming the file name you give to a module name; it imports the module and searches for your app. In this case it winds up looking at the `site` module, which is part of core python. I think if you're planning to use `flask run` it is probably easier for you to change your file name than for the flask team to change how flask handles the `FLASK_APP` variable.

**Comment by Kangaroux** [comment]
I'll post this in the flask repo as well. It seemed like a strange issue and happened when I installed sqlalchemy, but I guess I changed my entrypoint filename at the same time.
