### ISSUE TITLE
Any good examples on mocking sqlalchemy for MySQL Backend?

### ISSUE THREAD

**Issue by jkryanchou** [mitsuhiko/flask-sqlalchemy#509]
I found that some mysql specific `func` methods couldn't be tested with sqlite memory database which was usually be used to work with unittest cases. While there were some `func` such like `utc_timestamp()` only exist in MySQL.

**Comment by ThiefMaster** [comment]
you should use the same database in tests, development and production

**Comment by jkryanchou** [comment]
@ThiefMaster Using MySQL as my unittest database? While I have to setup a real MySQL db for unittesting. It was too heavy to get it work with my test cases. Any good mysql mock library or examples could you provide me to play the unittests with sqlalchemy?

**Comment by davidism** [comment]
Yes, you need the same type of database you're coding against. See #249 for how to use transactions to make testing faster. SQLAlchemy-Utils has a function for creating a test db from a connection string.

**Comment by jkryanchou** [comment]
@davidism While I still have to setup a real MySQL Database instance for unittest. Any good suggestions on setup mock db ? such as sqlite memory database. or anything else.

**Comment by ThiefMaster** [comment]
No, and as we already said, this is a **bad idea**. Unless you stay away from ALL features specific to your primary database it might not even work!

FYI, at least with Postgres it's quite easy to create a temporary server from a pytest fixture that's completely standalone.

**Comment by jkryanchou** [comment]
@ThiefMaster OK I got it. I cant agree with you more. With mock database we could not get fully test on the features which we integrated with my project code.  :+1:
