### ISSUE TITLE
Specify the unit of time for SQLALCHEMY_POOL_TIMEOUT in the docs

### ISSUE THREAD

**Issue by dumptyd** [mitsuhiko/flask-sqlalchemy#513]
I think it's in seconds, but I'm still not sure. http://flask-sqlalchemy.pocoo.org/2.1/config/?highlight=SQLALCHEMY_POOL_TIMEOUT

**Comment by sowmitranalla** [comment]
Hi, 

I have a feeling the unit of measurement changes based on the number, but I'm not sure either. 

I connect to an Azure SQL DB which disconnects idle connections in 30 mins. When this happens, the first time I try and run a query, I get a 500 and upon a subsequent reload with no code changes everything loads fine. 

With that in mind, and seeing the documentation say the default value is 10, I thought the following:
- if the connection pool was closing every 10 seconds, I would never see the issue. SQLAlchemy would close connections in the pool every 10 seconds and create new ones as needed. This is clearly not happening.

**Comment by davidism** [comment]
SQLAlchemy docs say its seconds, added that to our docs.
