### ISSUE TITLE
Declaring Column type 'UUID'

### ISSUE THREAD

**Issue by gserapio** [mitsuhiko/flask-sqlalchemy#515]
I've been trying to declare db.UUID as a column type in flask-sqlalchemy. I'm getting a sqlalchemy.exc.StatementError. Does flask-sqlalchemy support UUIDs as a column type?

**Comment by gserapio** [comment]
I think I got it to work! My code runs when I insert the `UUID` as a string and not a `uuid.UUID` object.


```
str(uuid.uuid4())
```

**Comment by ThiefMaster** [comment]
Correct, if you want to work with UUID objects instead of string UUIDs you have to use `UUID(as_uuid=True)` (not 100% sure about the argument name, check the SQLAlchemy docs)
