### ISSUE TITLE
"INSERT OR REPLACE" for duplicate constraint

### ISSUE THREAD

**Issue by alltheoptions** [mitsuhiko/flask-sqlalchemy#522]
How can i REPLACE when "sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed"
Using flask-sqlalchemy?

**Comment by ThiefMaster** [comment]
That's a SQLAlchemy question, not specific to Flask-SQLAlchemy.

**Comment by alltheoptions** [comment]
@ThiefMaster @davidism https://github.com/mitsuhiko/flask-sqlalchemy/issues/523
