### ISSUE TITLE
Missing file: test_sqlalchemy.py

### ISSUE THREAD

**Issue by xliiv** [mitsuhiko/flask-sqlalchemy#529]
`Readme`, `make` reference file:
test_sqlalchemy.py
There is no such file.

**Comment by ThiefMaster** [comment]
The new way of running tests is with `pytest`. Feel free to send a PR to update the docs! I would use this opportunity to replace `py.test` with the non-deprecated version `pytest` in this line: https://github.com/mitsuhiko/flask-sqlalchemy/blob/master/tox.ini#L5
