### ISSUE TITLE
sessions are sometimes not cleaned up post-request

### ISSUE THREAD

**Issue by mauritsd** [mitsuhiko/flask-sqlalchemy#531]
I've been debugging an issue in my flask-sqlalchemy app for the last few days in which new requests were given sessions that were not 'clean', i.e. they were in a rollback state or in a transactional context that was started hours before. The problems went away after I added a version of the post-request session cleanup handler for ```teardown_request``` instead of ```teardown_appcontext```: 
```
@app.teardown_request
def shutdown_session(response_or_exc):
    if app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN']:
        if response_or_exc is None:
            db.session.commit()

    db.session.remove()
    return response_or_exc
```

I realise that issues of this kind have been reported before (in #99 #379 #508 and possibly others) after which ```teardown_appcontext``` was found to be correct, but to me it seems very likely that there are at least some cases in which it is not. 

Is there a specific reason why ```teardown_request``` is not used? It seems to be the event handler that runs exactly at the time that flask-sqlalchemy would want to clean up sessions.

**Comment by ThiefMaster** [comment]
If you have e.g. a commandline script you usually have only an app context but not a request context. Using the app context should be enough, unless something else is very wrong in the app (if the app context is not torn down properly after a request it also means that `flask.g` is not cleared)

**Comment by mauritsd** [comment]
I see. The app I have is quite small and is close to the flask-sqlalchemy examples, so it seems unlikely to me that it's caused by anything I'm doing wrong (although that's of course still a possibility). It's not open source, but I'll see if I can write a test case that reproduces the problem. That may take some time, though, as the issue only happens intermittently...

**Comment by loveguoguo** [comment]
I have met the same problem, 
firstly, there was an error :OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (ConnectionResetError(104, 'Connection reset by peer'))"),
later , i got:StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back

it seems that the first error cause shutdown_session not called, or maybe db.session.remove not do what it should be

**Comment by mauritsd** [comment]
Sorry, this does seem to have been caused by me after all. I had a command-line tool that required an app context to be pushed onto the stack, but this bit of logic wasn't disabled when the app was setup for 'web mode'. Everything works as it's supposed to now!

If you think a warning in the docs about this is appropriate I will send a pull request later. I'll close this now.

**Comment by ThiefMaster** [comment]
I think this would rather be something for the Flask core. I wonder if it would make sense to even fail with an exception when the wsgi app callable point is called with an active app context. Please open an issue in the pallets/flask repo about it.

**Comment by jkryanchou** [comment]
I think it's better to provide pre/post hook on request as tornado which will be convenient for us to do it.

**Comment by jkryanchou** [comment]
I think it's better to provide pre/post hook on request as tornado which will be convenient for us to do it.
