### ISSUE TITLE
Using limit method before paginate method.

### ISSUE THREAD

**Issue by WaferJay** [mitsuhiko/flask-sqlalchemy#532]
Hi. When I use limit method before paginate, an InvalidRequestError will be thrown:

> InvalidRequestError: Query.order_by() being called on a Query which already has LIMIT or OFFSET applied. To modify the row-limited results of a Query, call from_self() first. Otherwise, call order_by() before limit() or offset() are applied.

Then, I found this in source code for this project:
https://github.com/mitsuhiko/flask-sqlalchemy/blob/c1e309a90822d2b8b1c0ca2d05949bbfb7005778/flask_sqlalchemy/__init__.py#L485

When I remove `order_by(None)`, the program works fine.

So, why use `order_by(None)` before `count()` in that line? Is it necessary?

**Comment by davidism** [comment]
For performance, ordering a query just to count it is expensive. Don't call `limit` if you're going to paginate, that's what paginate should do.
