### ISSUE TITLE
How to return dict or list[dict] from db.engine.execute(sql)

### ISSUE THREAD

**Issue by sjqzhang** [mitsuhiko/flask-sqlalchemy#539]
How to return dict or list[dict] from db.engine.execute(sql)

Example:
db=SQLAlchemy()
rows=db.engine.execute("select * from user")

json.dumps(rows)

**Comment by ThiefMaster** [comment]
This is not the right place for support questions.

**Comment by sjqzhang** [comment]
If I want to run a raw sql and get a dict object or list[dict] object ,could you tell me how?
