### ISSUE TITLE
Custom Session type is not used

### ISSUE THREAD

**Issue by blainehansen** [mitsuhiko/flask-sqlalchemy#545]
I've created a custom Session and Query object to allow me to use pandas dataframes with this library.

[I've overridden the `create_session` method of the `SQLAlchemy` class as recommended in the docs](http://flask-sqlalchemy.pocoo.org/2.2/api/#sessions), but when I try to use the custom session's `add_dataframe` method, I get this error:

```
AttributeError: 'scoped_session' object has no attribute 'add_dataframe'
```

Here is the code, with a simplified console output below:

```python
# in service code
print(type(self.db))
print(type(self.db.session))

ses = self.db.create_session()()
print(ses)
print(type(ses))
print(ses.add_dataframe)

# here's the line that creates the error
print(self.db.session.add_dataframe)

# in db code
class PandasSession(SignallingSession):
	def __init__(self, db, autocommit=False, autoflush=True, **options):
		print('this is created')
		super(PandasSession, self).__init__(db, autocommit, autoflush, **options)

	def add_dataframe(self, cls, dataframe, parse_index=False):
		# ... various pandas functionality ...

class PandasQuery(BaseQuery):
	# ... various pandas functionality ...

class CustomSQLAlchemy(SQLAlchemy):
	# ... various unrelated methods ...

	def create_session(self, options):
		print('this is called')
		return orm.sessionmaker(class_=PandasSession, db=self, **options)

db = CustomSQLAlchemy(query_class=PandasQuery)
```

```
root@a7ade1938bfa:/app# ./dev_application.sh

this is called
# ... various unrelated startup logs
this is called
# ... various unrelated startup logs

# at this point an html request is issued by curl

this is created
<class 'app.db.MultiTenantSQLAlchemy'>
<class 'sqlalchemy.orm.scoping.scoped_session'>
this is called
this is created
<sqlalchemy.orm.session.PandasSession object at 0x7f7aac7eb160>
<class 'sqlalchemy.orm.session.PandasSession'>
<bound method PandasSession.add_dataframe of <sqlalchemy.orm.session.PandasSession object at 0x7f7aac7eb160>>
172.17.0.1 - - [27/Sep/2017 23:26:15] "GET /pandas HTTP/1.1" 500 -
# ... a long stack trace
AttributeError: 'scoped_session' object has no attribute 'add_dataframe'
```

I'm confident this has something to do with wrapping the session with a scoped_session, but I don't know why or what to do about it.

Thank you in advance for your help!

**Comment by davidism** [comment]
Why does that method need to be on the session class? Does that work in plain SQLAlchemy? That is, create your `PandasSession`, pass it to a `sessionmaker`, pass that to a `scoped_session`.

**Comment by blainehansen** [comment]
I suppose that would be a decent alternative, putting these methods on the CustomSQLAlchemy object instead of the session. I still am confused about why this isn't working though. Perhaps I don't understand the sessionmaker / session system.

**Comment by davidism** [comment]
`scoped_session` only proxies the public API methods from `Session`. It will not proxy to custom methods. Bring that up with SQLAlchemy if you think it should change, but the answer's probably going to be "that's not how sessions are intended to be used / extended."

**Comment by justanr** [comment]
@davidism Is that fact something to be mindful of #456? e.g. accounting for it in the docs?

**Comment by davidism** [comment]
@justanr yes, that docs example wouldn't work. There are reasons to subclass the session, but adding custom methods isn't one of them.

**Comment by justanr** [comment]
Gotcha, I'll update them when I get a chance.

**Comment by davidism** [comment]
Oh, hmm. You should be able to override `commit`, never mind.
