### ISSUE TITLE
Why am I getting KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'?

### ISSUE THREAD

**Issue by billmcknight1953** [mitsuhiko/flask-sqlalchemy#549]
I get `KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'` with MySQL on 2.3.

**Comment by davidism** [comment]
When reporting bugs, please include a minimal example that reproduces the issue. I do not get this error in the test suite or my projects.

**Comment by billmcknight1953** [comment]
[CODE.txt](https://github.com/mitsuhiko/flask-sqlalchemy/files/1347434/CODE.txt)

Attached above is an outline of a three module flask program which produces the issue in Flask-SQLAcademy 2.3 but not in 2.1.   The "program" is sketchy in the sense that the exact models and mysql connections have been sketched.  I personally think the issue is how does one properly modularize model code and connections.

**Comment by ThiefMaster** [comment]
You create multiple Flask instances instead of importing one instance when you need it. That cannot work and causes this kind of problem.

**Comment by davidism** [comment]
And the reason for the error is that of the multiple apps you created, the one you're actually running wasn't registered with the extension, so the extension can't find the configuration. But as Thief said, this whole setup doesn't make sense. This would have been just as broken in 2.1, you just would have seen different errors eventually.
