### ISSUE TITLE
Attribute __table__ not set for classes using single table inheritance

### ISSUE THREAD

**Issue by quantus** [mitsuhiko/flask-sqlalchemy#560]
I'm trying to update Flask-Sqlalchemy from version 2.1 to the 2.3.1 on one application I'm maintaining (sqlalchemy version 1.1.14). The issue I'm having is that `__table__` attributes are not being set for classes that use single table inheritance. I would assume that the `__table__` attribute is always present on those classes. That is also how the pure sqlalchemy solution behaves.

Minimal code showing the issue:
```python
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class Item(db.Model):
    __tablename__ = 'item'

    id = db.Column(db.Integer, primary_key=True)
    info = db.Column(db.String(255))
    type = db.Column(db.String())

    __mapper_args__ = {
        'polymorphic_on': type
    }


class ItemA(Item):
    __mapper_args__ = {
        'polymorphic_identity': 'a'
    }


class ItemB(Item):
    __mapper_args__ = {
        'polymorphic_identity': 'b'
    }

assert ItemA.__tablename__ == 'item'
assert ItemB.__tablename__ == 'item'
assert ItemA.__table__ == Item.__table__  # This assertation fails
assert ItemB.__table__ == Item.__table__  # This assertation fails
```

Here is the pure sqlalchemy solution that passes:
```python
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Item(Base):
    __tablename__ = 'item'

    id = Column(Integer, primary_key=True)
    info = Column(String(255))
    type = Column(String())

    __mapper_args__ = {
        'polymorphic_on': type
    }


class ItemA(Item):
    __mapper_args__ = {
        'polymorphic_identity': 'a'
    }


class ItemB(Item):
    __mapper_args__ = {
        'polymorphic_identity': 'b'
    }

assert ItemA.__tablename__ == 'item'
assert ItemB.__tablename__ == 'item'
assert ItemA.__table__ == Item.__table__
assert ItemB.__table__ == Item.__table__
```

**Comment by davidism** [comment]
This is not possible given how the hook we're using works. Use SQLAlchemy's inspection API to discover information about models.

```python
m = db.inspect(ItemA)
print(m.mapped_table)
print(m.mapped_table.name)
```

cc @zzzeek

**Comment by quantus** [comment]
Thanks for the fast response!

That sounds a bit unexpected behaviour as it's not the same as with pure sqlalchemy, but I do see that the proposed way of accessing the information with inspection API is completely reasonable.

The actual code that tries to access the `__table__` is inside sqlalchemy-searchable [source](https://github.com/kvesteri/sqlalchemy-searchable/blob/26d225e5318577a56a9ecac3e07755af7eabfa5c/sqlalchemy_searchable/__init__.py#L312), so the fix needs to be implemented there. I'll report this issue to that package.

**Comment by davidism** [comment]
Actually, I can fix this. But you should still use `inspect` when possible.

**Comment by davidism** [comment]
Released 2.3.2. `pip install -U flask-sqlalchemy`

**Comment by quantus** [comment]
Thank you for the fix, it fixes the issue in the minimal case I showed. Unfortunately it seems that the minimal case I created was a bit too minimalistic when compared to what actually happens with the sqlalchemy-searchable. The sqlalchemy-searchable tries to read the `__table__` attribute in `instrument_class` event listener, and even with the Flask-Sqlalchemy version 2.3.2 the `__table__` attribute is not set at that point of time.

I tried to use the `inspect` to get the list of table's columns for sqlalchemy-searchable, but for some reason that raises `NoInspectionAvailable` exception. I'm not sure if there is some limitations whether the `inspect` can be called at that point of time. The full exception text is `NoInspectionAvailable: No inspection system is available for object of type <class 'flask_sqlalchemy.model.DefaultMeta'>`

Here is the code that can be used to reproduces both issues (`__table__` not set during event listener and `inspect` raising `NoInspectionAvailable` exception.):
 
```python
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import event
import sqlalchemy as sa


db = SQLAlchemy()


def process_mapper(mapper, cls):
    assert cls.__table__ is not None  # This assertation fails for ItemA
    if cls.__table__ is None:
        db.inspect(cls)  # This raises NoInspectionAvailable exception for ItemA

event.listen(
    sa.orm.mapper, 'instrument_class', process_mapper
)


class Item(db.Model):
    __tablename__ = 'item'

    id = db.Column(db.Integer, primary_key=True)
    info = db.Column(db.String(255))
    type = db.Column(db.String())

    __mapper_args__ = {
        'polymorphic_on': type
    }


class ItemA(Item):
    __mapper_args__ = {
        'polymorphic_identity': 'a'
    }
```

**Comment by davidism** [comment]
OK, I see why this is failing, the event is triggered while the class is being mapped, which is before `__init__` can reset it.

But you already have the mapper at that point, you don't need to use inspect there. `mapper.mapped_table`

**Comment by quantus** [comment]
I think the easiest way of fixing this is to make the change to sqlalchemy-searchable, so I made an PR there to fix this issue: https://github.com/kvesteri/sqlalchemy-searchable/pull/64

Thanks for your help!
