### ISSUE TITLE
init_app does not create the app property

### ISSUE THREAD

**Issue by cal97g** [mitsuhiko/flask-sqlalchemy#570]
I would like to access the app object from within some of my models. This works fine when I initialise the SQLAlchemy instance in the usual way.

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
app.config['SOME_KEY'] = "SOME VAL"
db = SQLAlchemy(app)


class User(db.Model):
    print db.app
    print db.app.config
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

    def __repr__(self):
        return '<User %r>' % self.username

db.create_all()
User.query.all()
```

However, if I pass the app with init_app I get

>  RuntimeError: application not registered on db instance and no applicationbound to current context

See code:

```
from flask import Flask
from __init__ import dbc
from models import Server

app = Flask("cool app dude")
dbc.init_app(app)

Server.query.all()
```

I am working on a fix for this issue.

**Comment by ThiefMaster** [comment]
This is intentional. You need to run the code inside a Flask app context (`with app.app_context(): ...`) when using `init_app()`

**Comment by cal97g** [comment]
@ThiefMaster 
Even with app.app_context() the app is not registered on init_app. The behaviour between __init__ and init_app should not be different. I should not be able to access app with one initialisation method and not with another.

**Comment by ThiefMaster** [comment]
This difference **is** intentional. If you pass the app directly it sets it for the sake of convenience.

**Comment by cal97g** [comment]
I see. You can just set the db.app = app. Not sure why I didn't think of this initially.
