### ISSUE TITLE
Add shorthand method "save()" and "delete()" for model

### ISSUE THREAD

**Issue by greyli** [mitsuhiko/flask-sqlalchemy#575]
Hi, guys! I thought it would be helpful if we can add two shorthand method: the `save()` to commit a record, the `delete()` to delete a record, just like what we do in MongoEngine.

With this two methods, the code below:
```python
>>> post = Post(title='foo')
>>> db.session.add(post)
>>> db.session.commit()
```
will be simplified to this:
```python
>>> post = Post(title='foo')
>>> post.save()
```
and the code below:
```python
>>> db.session.delete(post)
>>> db.session.commit()
```
will be simplified to this:
```python
>>> post.delete()
```
If it's possible, I'm pleased to make a PR.

**Comment by ThiefMaster** [comment]
Strong :-1: from me. This is not the sqlalchemy way and I'm against diverting that much from what you do in vanilla sqlalchemy. Also, committing single objects instead of everything at the end seems like a bad idea...

**Comment by greyli** [comment]
Oh, I didn't realize it before. Is it a bad practice to subclass `Model` and add these methods in the personal application? 

In mostly condition, you only need to operate one object at a time. If I need to save a list of objects, surely I will use the original method.

**Comment by HashRocketSyntax** [comment]
I came here looking for .save()
![image](https://user-images.githubusercontent.com/16389820/58140299-adde7580-7c0c-11e9-8b98-cc79c8f80cbe.png)
