### ISSUE TITLE
Please provide example self referencing many-to-{many/one} field

### ISSUE THREAD

**Issue by somenxavier** [mitsuhiko/flask-sqlalchemy#579]
For example implementing a Follower to Follower person

**Comment by davidism** [comment]
The SQLAlchemy docs already have an example.

**Comment by somenxavier** [comment]
> The SQLAlchemy docs already have an example.
So remove all documentation

**Comment by ThiefMaster** [comment]
It's nothing special to Flask-SQLAlchemy, which is a thin wrapper  of SQLAlchemy. No good reason to replicate tons of documentation.
