### ISSUE TITLE
Update to SQLAlchemy 1.2

### ISSUE THREAD

**Issue by maxnordlund** [mitsuhiko/flask-sqlalchemy#581]
It has been released, yay! I assume flask-alchemy want to update at some point. So I thought why not create an issue to track progress.

From what I can tell by this [migration guide](http://docs.sqlalchemy.org/en/latest/changelog/migration_12.html), it doesn't seem to be too bad. Mostly advance stuff, after_rollback triggers before expiration of objects and scope keyword removed from scoped_session seems the most relevant. But as always, one should scrutinize the changelog thoroughly.

**Comment by davidism** [comment]
What's not working with the new version? Typically there's nothing that needs to be done on our end. If there are specific issues please open specific tickets.

**Comment by ThiefMaster** [comment]
I think it worked fine. Last year I tried installing 1.2beta in my application that also uses flask-sqlalchemy and everything still worked fine.

**Comment by maxnordlund** [comment]
They do drop support for python 2.6, and have only tested on 3.3 and 3.6. But the [setup.py](https://github.com/mitsuhiko/flask-sqlalchemy/blob/f465142ea1643b4f0fe50540780ef9a6bf2c7e53/setup.py) does not reflect that constraint, yet allows SA ≥ 0.8.0 (and flask ≥ 0.10).

I'll be honest and say I'm not totally familiar with pips version resolution algorithm, but I think it would be better if the constraints of flask-sqlalchemy reflected the constraints of the source packages, right?

If nothing else, updating the README should suffice to reduce developer confusion.

**Comment by davidism** [comment]
What's not clear about them right now? "It requires SQLAlchemy 0.8 or higher." 1.2 is higher than 0.8.

**Comment by maxnordlund** [comment]
SQLAlchemy doesn't support python 2.6, flask-sqlalchemy does according to setup.py Same for python ≤ 3.5

**Comment by davidism** [comment]
Yes, your environment has to conform to the requirements of all your dependencies. If you use a version that doesn't support 2.6, don't use 2.6. I don't think our docs need to be updated for that.
