### ISSUE TITLE
SQLAlchemy 1.2 not supporting python 2.6 causes travis to fail

### ISSUE THREAD

**Issue by asoderman** [mitsuhiko/flask-sqlalchemy#587]
I opened a pull request earlier and travis had failed because SQLAlchemy no longer supports python 2.6. If python 2.6 is still going to be supported by flask-sqlalchemy then an older version of SQLAlchemy needs to be used.

Where travis failed:
```
Collecting SQLAlchemy>=0.8.0 (from Flask-SQLAlchemy==2.3.2.dev20180120) 
Downloading SQLAlchemy-1.2.1.tar.gz (5.5MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cHubfe/SQLAlchemy/setup.py", line 16, in <module>
        raise Exception("SQLAlchemy requires Python 2.7 or higher.")
    Exception: SQLAlchemy requires Python 2.7 or higher.
```

[Source](https://docs.sqlalchemy.org/en/latest/changelog/migration_12.html#targeting-python-2-7-and-up)

**Comment by hugovk** [comment]
Here's the pip installs for Flask-SQLAlchemy from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   85.8% |        645,538 |
| 3.6            |    7.7% |         57,602 |
| 3.5            |    3.8% |         28,411 |
| 3.4            |    2.5% |         18,775 |
| 2.6            |    0.1% |            868 |
| 3.7            |    0.1% |            532 |
| 3.3            |    0.0% |            346 |
| None           |    0.0% |              4 |
| 3.2            |    0.0% |              1 |

Source: `pypinfo --start-date -51 --end-date -21 --percent --pip --markdown Flask-SQLAlchemy pyversion`

How about dropping 2.6? It's been EOL for over 4 years.

**Comment by ThiefMaster** [comment]
:+1: on getting rid of 2.6

**Comment by hugovk** [comment]
Please see PR https://github.com/mitsuhiko/flask-sqlalchemy/pull/588.
