### ISSUE TITLE
Applying TypeDecorator to db.Column

### ISSUE THREAD

**Issue by pn2** [mitsuhiko/flask-sqlalchemy#601]
I am not sure whether this is a feature request or simply a problem arising from my limited understanding of how to access sqlalchemy's underlying functionality. 

I would like to apply a [TypeDecorator](http://docs.sqlalchemy.org/en/latest/core/custom_types.html) to a table column, to pre-process data that is assigned. The column is declared in the 'usual way':

    class User(db.Model):
        name = db.Column(db.String)

It would be nice if that was possible through additional arguments to 'db.Column'. But maybe there is a different obvious solution...

**Comment by ThiefMaster** [comment]
`db.Column()` is *literally* the same as SQLAlchemy's `Column()`. You can even use them interchangeably. 

AFAIK using type decorators always happens outside declaring a model since it basically defines a new type - and then you use that new type in your model.
