### ISSUE TITLE
Is it possible to use CTE with filters?

### ISSUE THREAD

**Issue by darwinyip** [mitsuhiko/flask-sqlalchemy#604]
How can I achieve the following?
`Restaurant.query(Restaurant.camis).filter(Restaurant.active).cte()`
`TypeError: 'BaseQuery' object is not callable`

Removing the query arguments work:
 `Restaurant.query.filter(Restaurant.active).cte()`
`<sqlalchemy.sql.selectable.CTE at 0x7fe18cebfe10; %(140606708645392 anon)s>`

**Comment by ThiefMaster** [comment]
`Foo.query` is an alias for `db.session.query(Foo)`; for anything beyond that, use `db.session.query(...)` directly.
