### ISSUE TITLE
Running pytest leads to "... is already defined for this MetaData instance"

### ISSUE THREAD

**Issue by chrismeh** [mitsuhiko/flask-sqlalchemy#614]
I am currently working on a class that provides Authentication functionality. The class itself depends on a UserRepository, that basically just wraps db.session. The code kind of looks like this:

AuthenticationService
Please note the type hint in the class constructor.

```python
from repository.user import UserRepository

class UnauthorizedException(Exception):
    pass

class AuthenticationService:
    def __init__(self, user_repository: UserRepository):
        self.user_repository = user_repository

    def authenticate(self, username, password):
        user = self.user_repository.find_by_username(username)
        if not user:
            raise UnauthorizedException("Invalid credentials.")
```

User Model
```python
from werkzeug.security import generate_password_hash
from extensions import db

class User(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(80), nullable=False)
    last_name = db.Column(db.String(80), nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(120), nullable=False)
    active = db.Column(db.Boolean, server_default=db.true(), default=True, nullable=False)

    def set_password(self, password):
        self.password = generate_password_hash(password)
```

User Repository
```python
from repository.abstract import AbstractRepository
from model.user import User

class UserRepository(AbstractRepository):
    def __init__(self, session):
        super().__init__(session, User)

    def find_by_username(self, username):
        return self._session.query(self.entity_type).filter_by(username=username).first()
```

Additionally, I wrote a simple test for the AuthenticationService
```python
from service.authentication import AuthenticationService, UnauthorizedException
import pytest

def test_authorize_when_given_unknown_username_throws_exception(mocker):
    user_repo_mock = mocker.MagicMock()
    user_repo_mock.find_by_username.return_value = None

    auth_service = AuthenticationService(user_repo_mock)

    with pytest.raises(UnauthorizedException):
        auth_service.authenticate("some_random_username", "some_password")
```

When running this using pytest, I get the following error message:

sqlalchemy.exc.InvalidRequestError: Table 'user' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

When removing the type hint (and thus the import) from the AuthenticationService, this error disappears. It also doesn't even come up when I use the native SQLAlchemy declarative base in the User model. Even though the error message seems to be a SQLAlchemy native, this kind of makes me feel like the reason for this is somewhere in Flask-SQLAlchemy when used with pytest.

I'm using Flask-SQLAlchemy 2.3.2, SQLAlchemy 1.2.6 and pytest 3.5.0

**Comment by leandrocosta26** [comment]
Hi, chrismeh.
I had a similar problem recently, but it occurs because the database I was using had that name registered. I solved it when I changed its name to something like `user_account` for example. Which database are you using.

**Comment by chrismeh** [comment]
Hi leandrocosta26,

sorry for not getting back to you earlier. Unfortunately, just changing the table name to something else than `user` didn't help. I just updated to Python 3.6 yesterday (been using 3.5 for a while now) and I can't seem to reproduce this error anymore. I will investigate into this more though.
