### ISSUE TITLE
Avoid warning when inserting blob data

### ISSUE THREAD

**Issue by zingdle** [mitsuhiko/flask-sqlalchemy#615]
The column is `db.Column(db.PickleType)` 

I got 
```
Warning: (1300, "Invalid utf8 character string: '800495'")
  result = self._query(query)
```
when trying to insert the pickle type data in a `utf-8` charset database. [This](https://stackoverflow.com/questions/36849144/how-to-avoid-encoding-warning-when-inserting-binary-data-into-a-blob-column-in-m) may help. 

I'm using `SQLAlchemy==1.2.6` and `Flask-SQLAlchemy==2.3.2` and `Flask==0.12.2`.

**Comment by davidism** [comment]
This warning comes from SQLAlchemy, not Flask-SQLAlchemy.
