### ISSUE TITLE
Error on connect(): Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by dhhagan** [mitsuhiko/flask-sqlalchemy#623]
Setup:

Python 3.5.2 on Ubuntu 16.04

    flask-sqlalchemy==2.3.2
    sqlalchemy==1.1.15
    flask==0.12
    pymysql==0.7.11

Connection string:

    SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://<username>:<pswd>@localhost::3306/<db>'

Increasingly, I see a bunch of errors pop up on Sentry with the error message 

`Error on connect(): Can't convert 'bytes' object to str implicitly`

The traceback threw me off for a bit, but it appears it is due to the database connection. I'm not 100% sure this is on flask-sqlalchemy (most likely sqlalchemy itself or pymysql), but I thought I would see if anyone else has seen this issue pop up? 

An example traceback can be seen [here](https://sentry.io/share/issue/b61e0a9945a048a29ceb8976ff9bcd91/).

**Comment by davidism** [comment]
Given that all of the traceback occurs in SQLAlchemy code, not Flask-SQLAlchemy, closing this.
