### ISSUE TITLE
Unable to insert Date type data

### ISSUE THREAD

**Issue by 787771075** [mitsuhiko/flask-sqlalchemy#624]
Note: not Datetime type，I searched for similar problems on the Internet and found that they were all of datetime type.

always report errors when I trying to insert a Date type data.
Whether I use string or datatime.data type, all errors are returned.
But the Time type is Ok with a string

**Comment by alanhamlett** [comment]
I'm able to insert `Date` objects. You will need to provide more info and an error message traceback.
