### ISSUE TITLE
Wait until database comes up

### ISSUE THREAD

**Issue by TheoAndersen** [mitsuhiko/flask-sqlalchemy#630]
Using a docker setup, the database will often not be up yet, when the application is started.

Now i can use a shell script to not start the application, before i know the database is up. But it would be easier to just wrap db.init_app(app) or something, so that it would wait and retry until the database was up.

Is there any known way to do this?

**Comment by ThiefMaster** [comment]
Besides the fact that running a production database in a Docker container is questionable: Why is this a problem? Worst case is that a request arriving before the DB is up gets a 500 error - the application never accesses the database at import/startup time (unless you do weird things).

**Comment by davidism** [comment]
While setting up the app, add a loop that does "select 1" until it doesn't get an error. Add sleep/timeout for nicer behavior.

**Comment by TheoAndersen** [comment]
@ThiefMaster 
Docker is a great tool for testing/development scenarios (not only for production). And in these scenarios you can't be sure that the database is fully started, when the application starts. Having the application able to try again a few times when it starts up, would make this more smooth.

@davidism 
Thanks, Ill do something like that.
