### ISSUE TITLE
TypeError: unhashable type: 'list' with Oracle Sequence flask-sqlalchemy

### ISSUE THREAD

**Issue by mjdileep** [mitsuhiko/flask-sqlalchemy#639]
I'm trying to make **id** column **auto-increment** with **Sequence** in Oracle 12c as shown bellow:
 ```
class APIKey(db.Model):
     __tablename__ = 'APIKey'
    apikey_id_seq = db.Sequence('apikey_id_seq', metadata=db.Model.metadata)
    id = db.Column(db.Integer, apikey_id_seq, server_default= apikey_id_seq.next_value(),primary_key=True)
    name = db.Column(db.String(100))
    username = db.Column(db.String(20), index=True, unique=True)
    key = db.Column(db.String(40))
```
I created the the schema and add an object like bellow:
```
if __name__ == '__main__':
    db.drop_all()
    db.create_all()
    apikey = FingerAPIKey(name='dileep', username='dileep', key='1234')
    db.session.add(apikey)
    db.session.commit()
    app.run(host=host, port=port)
```
During the commit I get following error:
```
File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1688, in _register_newly_persistent
    if _none_set.intersection(instance_key[1]) and \
TypeError: unhashable type: 'list'
```

**Comment by davidism** [comment]
This appears to be an issue either with SQLAlchemy or with your code, not Flask-SQLAlchemy. This extension is just a wrapper around SQLAlchemy, it shouldn't be doing anything to affect this.

**Comment by mjdileep** [comment]
Yes @davidism The error was on SQLAlchemy side, I resolved it by adding following two lines in venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py file.
![image](https://user-images.githubusercontent.com/6938724/45628936-d842c680-bab2-11e8-92a7-32303eaa739d.png)
