### ISSUE TITLE
new pypi release // release cycle

### ISSUE THREAD

**Issue by Birne94** [mitsuhiko/flask-sqlalchemy#654]
Are there any plans on releasing a new version of this package any time soon? In particular, we are interested in the changes of #613 and are currently working around this by subclassing the base query ourselves.

I know it is tedious to be asked over and over again for now releases, but as a user I am not sure if there will be a release any time soon or if it is better to just roll out our own workaround/fixes. Maybe an official release cycle or some sort of release-milestones of blocking issues would be helpful? 

Are there any open issues or problems blocking a new release?

**Comment by davidism** [comment]
Yes, this is still supported, no I can't give a firm schedule for a next release, yes we would appreciate sustained help towards a new release.
