### ISSUE TITLE
running postgresdb with gunicorn and multiple workers crashes

### ISSUE THREAD

**Issue by theo-walton** [mitsuhiko/flask-sqlalchemy#656]
I get the following error:

`sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"`

from line:
`DB.create_all(app=APP)`

when I run my flask app on gunicorn with 4 workers.

My setup looks like this:

```
DB = SQLAlchemy()

class Group(DB.Model):
    __tablename__ = 'group'
    id = DB.Column(DB.Integer, primary_key=True)
    name = DB.Column(DB.String(), unique=True, nullable=False)

APP = Flask(__name__)
APP.config.from_mapping(
    SQLALCHEMY_DATABASE_URI='postgres://........',
    SQLALCHEMY_TRACK_MODIFICATIONS=False
)

DB.init_app(APP)
DB.create_all(app=APP)
...
```

**Comment by ThiefMaster** [comment]
`DB.create_all(app=APP)` does not belong in code that runs at import time or startup or any other code executed by the web server. It should be in a CLI you execute manually.
