### ISSUE TITLE
Install the package error in pycharm

### ISSUE THREAD

**Issue by bowen24** [mitsuhiko/flask-sqlalchemy#657]
When I used flask_sqlalchemy in a flask project, I found that a quick install was not possible.
Then I tried installing flask_sqlalchemy in pipenv with shell and succeeded.
However, it is still not available in pycharm
Later, the reason for the problem was found in pycharm's package manager,that's what we call "Available Packages".
If I search for "flask_sqlalchemy," I won't find it.
But if I search for "flask-sqlalchemy," I get it.
The difference is between "-" and "_".
The code looks normal after installation, but the code is named "flask_sqlalchemy".
An error is reported if "flask-sqlalchemy" is used in the code, so the package can only be installed manually.
I wonder if anyone has found this BUG.
This paragraph is all machine translation, I hope you can understand : )

**Comment by ThiefMaster** [comment]
report it to the pycharm devs, they should apply the same package name normalization rules pypi applies.
