### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by gongshuiwen** [mitsuhiko/flask-sqlalchemy#658]
`C:\Users\zhang\Desktop\PyCharm\my-webapp\venv\Scripts\python.exe C:/Users/zhang/Desktop/PyCharm/my-webapp/www/app.py
Traceback (most recent call last):
  File "C:/Users/zhang/Desktop/PyCharm/my-webapp/www/app.py", line 7, in <module>
    from sqlalchemy import event
ImportError: cannot import name 'event'`

**Comment by ThiefMaster** [comment]
Not related to the extension; probably you have a `sqlalchemy.py` file there

**Comment by gongshuiwen** [comment]
Ok, thank you.
