### ISSUE TITLE
Proper model directory structure

### ISSUE THREAD

**Issue by yuvadm** [mitsuhiko/flask-sqlalchemy#97]
I found no mention in the docs about the proper way to structure models in a Flask app. Right now I have this:

``` python
# app.py
db = SQLAlchemy(app)
```

and:
```python
# models.py
from app import db
class MyModel(db.Model):
# ...
```

But this means I have a circular dependency once I try to do:
```python
# app.py
from models import MyModel
```

It's worth mentioning how this should be done in the docs.

**Comment by immunda** [comment]
This isn't a Flask-SQLAlchemy issue per se, it largely depends of the structure of your app.

There's plenty of guides which outline various different ways of structuring a Flask app which includes Flask-SQLAlchemy.
